return function()
    return {
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Fences:GetChildren()[6],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Fences:GetChildren()[5],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Fences:GetChildren()[7],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Fences:GetChildren()[8],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Fences:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Fences:GetChildren()[10],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Fences:GetChildren()[2],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Fences:GetChildren()[12],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Fences:GetChildren()[14],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Fences:GetChildren()[13],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Fences:GetChildren()[15],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Fences:GetChildren()[16],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Fences:GetChildren()[17],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Fences:GetChildren()[18],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Fences:GetChildren()[19],
        workspace.ClientParts.ClientSidedObjects.PushBoxButton.Part,
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Fences:GetChildren()[3],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Part,
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"]:GetChildren()[1]:GetChildren()[20],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"]:GetChildren()[1]:GetChildren()[21],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"]:GetChildren()[2]:GetChildren()[20],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"]:GetChildren()[2]:GetChildren()[21],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Plank,
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"]:GetChildren()[4]:GetChildren()[20],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"]:GetChildren()[4]:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"]["Telephone Line"]:GetChildren()[4]:GetChildren()[2],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"]["Telephone Line"]:GetChildren()[5],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"]["Telephone Line"]:GetChildren()[2]:GetChildren()[4],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[21],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[32],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Clouds:GetChildren()[7],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Clouds:GetChildren()[2],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Clouds:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Clouds:GetChildren()[3],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Clouds:GetChildren()[4],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Clouds:GetChildren()[5],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Clouds:GetChildren()[6],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Clouds:GetChildren()[8],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Clouds:GetChildren()[9],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Clouds:GetChildren()[10],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Clouds:GetChildren()[25],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Clouds:GetChildren()[26],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Clouds:GetChildren()[27],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Clouds:GetChildren()[28],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Clouds:GetChildren()[29],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Clouds:GetChildren()[30],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Clouds:GetChildren()[31],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Clouds:GetChildren()[32],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Clouds:GetChildren()[33],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Clouds:GetChildren()[38],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Clouds:GetChildren()[39],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Clouds:GetChildren()[40],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Clouds:GetChildren()[41],
        workspace.Towers.ToDM.Obby["Floor 10 (Surface)"].Clouds:GetChildren()[42],
        workspace.ClientParts.ClientSidedObjects:GetChildren()[27]:GetChildren()[1],
        workspace.Towers.ToDM.Frame.Ground:GetChildren()[5],
        workspace.Towers.ToDM.Frame.Ground:GetChildren()[11],
        workspace.Towers.ToDM.Frame.Ground:GetChildren()[6],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[20],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[7],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[12],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[10],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[13],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[3],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[4],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[5],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[15],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[16],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[37],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[36],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[33],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[32],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[31],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[30],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[9],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[19],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[21],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[83],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[87],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[152],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[154],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[88],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[43],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[101],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[72],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[50],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[51],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[52],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[53],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[54],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[55],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[25],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[56],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[57],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[58],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[59],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[60],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[61],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[62],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[63],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[64],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[65],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[66],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[67],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[68],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[69],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[70],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[109],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[126],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[113],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[114],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[130]:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[130]:GetChildren()[2],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[130]:GetChildren()[3],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[130]:GetChildren()[4],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[130]:GetChildren()[5],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[130]:GetChildren()[6],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[130]:GetChildren()[7],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[130]:GetChildren()[8],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[130]:GetChildren()[9],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[130]:GetChildren()[10],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[130]:GetChildren()[11],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[130]:GetChildren()[12],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[130]:GetChildren()[13],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[130]:GetChildren()[14],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[130]:GetChildren()[15],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[130]:GetChildren()[16],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[130]:GetChildren()[17],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[130]:GetChildren()[18],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[130]:GetChildren()[19],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[130]:GetChildren()[20],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[128],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[40]:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[40]:GetChildren()[2],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[40]:GetChildren()[3],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[40]:GetChildren()[4],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[40]:GetChildren()[5],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[40]:GetChildren()[6],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[40]:GetChildren()[7],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[40]:GetChildren()[8],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[40]:GetChildren()[9],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[40]:GetChildren()[10],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[40]:GetChildren()[11],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[40]:GetChildren()[12],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[40]:GetChildren()[13],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[40]:GetChildren()[14],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[40]:GetChildren()[15],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[40]:GetChildren()[16],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[40]:GetChildren()[17],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[40]:GetChildren()[18],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[40]:GetChildren()[19],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[40]:GetChildren()[20],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[131],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[135],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[139],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[149],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[24],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[168],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[169],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[170],
        workspace.Towers.ToDM.Obby["Floor 9 (Dirt)"]:GetChildren()[171],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[3],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[81],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[82],
        workspace.ClientParts.ClientSidedObjects["Memory Platforms"].Group:GetChildren()[4],
        workspace.ClientParts.ClientSidedObjects["Memory Platforms"].Group:GetChildren()[5],
        workspace.ClientParts.ClientSidedObjects["Memory Platforms"].Group:GetChildren()[6],
        workspace.ClientParts.ClientSidedObjects:GetChildren()[9]:GetChildren()[3]:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects:GetChildren()[9]:GetChildren()[3]:GetChildren()[2],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[83],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[84],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[85],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[88],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]:GetChildren()[19],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]:GetChildren()[24],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]:GetChildren()[20],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]:GetChildren()[22],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]:GetChildren()[23],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]:GetChildren()[31],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]:GetChildren()[32]:GetChildren()[3],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]:GetChildren()[32]:GetChildren()[2],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]:GetChildren()[9],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[7],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[8],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[9],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Curve:GetChildren()[20],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Curve:GetChildren()[19],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Curve:GetChildren()[18],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Curve:GetChildren()[17],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Curve:GetChildren()[16],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Curve:GetChildren()[15],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Curve:GetChildren()[14],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Curve:GetChildren()[13],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Curve:GetChildren()[12],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Curve:GetChildren()[11],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Curve:GetChildren()[10],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Curve:GetChildren()[9],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Curve:GetChildren()[8],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Curve:GetChildren()[7],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Curve:GetChildren()[6],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Curve:GetChildren()[5],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Curve:GetChildren()[4],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Curve:GetChildren()[3],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Curve:GetChildren()[2],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Curve:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[10],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[11],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[12],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[13],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[14],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[15],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[16],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[17],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[18],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[19],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[20],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[21],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[22],
        workspace.ClientParts.ClientSidedObjects.DistanceAnchoringObjects:GetChildren()[11]:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects.DistanceAnchoringObjects:GetChildren()[12]:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects.DistanceAnchoringObjects:GetChildren()[13]:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects.DistanceAnchoringObjects:GetChildren()[14]:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects.DistanceAnchoringObjects:GetChildren()[15]:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects.DistanceAnchoringObjects:GetChildren()[16]:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[23],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[24],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[36],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[37],
        workspace.ClientParts.ClientSidedObjects.DistanceAnchoringObjects:GetChildren()[16]:GetChildren()[2],
        workspace.ClientParts.ClientSidedObjects.DistanceAnchoringObjects:GetChildren()[15]:GetChildren()[2],
        workspace.ClientParts.ClientSidedObjects.DistanceAnchoringObjects:GetChildren()[14]:GetChildren()[2],
        workspace.ClientParts.ClientSidedObjects.DistanceAnchoringObjects:GetChildren()[13]:GetChildren()[2],
        workspace.ClientParts.ClientSidedObjects.DistanceAnchoringObjects:GetChildren()[12]:GetChildren()[2],
        workspace.ClientParts.ClientSidedObjects.DistanceAnchoringObjects:GetChildren()[11]:GetChildren()[2],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[38],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[41],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[48],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[49],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[50],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[51],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[52],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[53],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[54],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Other:GetChildren()[2],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Other:GetChildren()[3],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Other:GetChildren()[4],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Other:GetChildren()[5],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Other:GetChildren()[6],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Other:GetChildren()[7],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Other:GetChildren()[8],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Other:GetChildren()[9],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Other:GetChildren()[10],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Other:GetChildren()[11],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Other:GetChildren()[12],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Other:GetChildren()[13],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Other:GetChildren()[14],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Other:GetChildren()[15],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Other:GetChildren()[16],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Other:GetChildren()[17],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Other:GetChildren()[18],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[55],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[56],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[76],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Other:GetChildren()[25],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Other:GetChildren()[24],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"].Other:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects:GetChildren()[3]:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[86],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]["Rectangular Parts"]:GetChildren()[87],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]:GetChildren()[12],
        workspace.Towers.ToDM.Obby["Floor 8-7 (Gray Cavern)"]:GetChildren()[11],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[37],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[36],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[31],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[32],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[2],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[3],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[4],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[5],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[6],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[7],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[8],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]:GetChildren()[6]:GetChildren()[2],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]:GetChildren()[6]:GetChildren()[3],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]:GetChildren()[2]:GetChildren()[2],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]:GetChildren()[2]:GetChildren()[3],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]:GetChildren()[1]:GetChildren()[2],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]:GetChildren()[1]:GetChildren()[3],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[9],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[10],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[12],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[11],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[13],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[14],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[15],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[16],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[17],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[18],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[19],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[20],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[21],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[23],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[25],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[24],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[26],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[27],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[28],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[29],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (First Section)"]:GetChildren()[30],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (Second Section)"]:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects.DistanceAnchoringObjects:GetChildren()[17]:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects.DistanceAnchoringObjects:GetChildren()[18]:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects.DistanceAnchoringObjects:GetChildren()[19]:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects.DistanceAnchoringObjects:GetChildren()[20]:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects.DistanceAnchoringObjects:GetChildren()[21]:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects.DistanceAnchoringObjects:GetChildren()[23]:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects.DistanceAnchoringObjects:GetChildren()[22]:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (Second Section)"]:GetChildren()[2],
        workspace.ClientParts.ClientSidedObjects:GetChildren()[10]:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects:GetChildren()[2]:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects:GetChildren()[11]:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects:GetChildren()[14]:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (Second Section)"]:GetChildren()[3],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"].Other:GetChildren()[10],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (Third Section)"]:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (Third Section)"]:GetChildren()[2],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (Third Section)"]:GetChildren()[3],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (Third Section)"]:GetChildren()[4],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (Third Section)"]:GetChildren()[5],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (Third Section)"]:GetChildren()[6],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (Third Section)"]:GetChildren()[7],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (Third Section)"]:GetChildren()[8],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (Third Section)"]:GetChildren()[9],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (Third Section)"]:GetChildren()[11],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (Third Section)"]:GetChildren()[10],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"]["Ice (Third Section)"]:GetChildren()[12],
        workspace.Towers.ToDM.Obby["Floor 6 (Ice)"].Other:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Obstacles:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Obstacles:GetChildren()[2],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Obstacles:GetChildren()[4],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Obstacles:GetChildren()[24],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Obstacles:GetChildren()[5],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Obstacles:GetChildren()[6],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Obstacles:GetChildren()[7],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Obstacles:GetChildren()[8],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Curve:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Curve:GetChildren()[2],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Curve:GetChildren()[3],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Curve:GetChildren()[4],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Curve:GetChildren()[5],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Curve:GetChildren()[6],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Curve:GetChildren()[7],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Curve:GetChildren()[8],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Curve:GetChildren()[9],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Curve:GetChildren()[10],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Curve:GetChildren()[11],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Curve:GetChildren()[12],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Curve:GetChildren()[13],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Curve:GetChildren()[14],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Curve:GetChildren()[15],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Curve:GetChildren()[16],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Obstacles:GetChildren()[9],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Obstacles:GetChildren()[10],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Obstacles:GetChildren()[11],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Obstacles:GetChildren()[12],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Obstacles:GetChildren()[13],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Obstacles:GetChildren()[14],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Obstacles:GetChildren()[15],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Obstacles:GetChildren()[16],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Obstacles:GetChildren()[17],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Obstacles:GetChildren()[18],
        workspace.Towers.ToDM.Obby["Floor 5 (Black Cavern)"].Obstacles:GetChildren()[19],
        workspace.Towers.ToDM.Obby["Layer 4 (Button Challenges)"]:GetChildren()[6],
        workspace.Towers.ToDM.Obby["Layer 4 (Button Challenges)"]:GetChildren()[7],
        workspace.Towers.ToDM.Obby["Layer 4 (Button Challenges)"]:GetChildren()[8],
        workspace.Towers.ToDM.Obby["Layer 4 (Button Challenges)"]:GetChildren()[9],
        workspace.Towers.ToDM.Obby["Layer 4 (Button Challenges)"]:GetChildren()[10],
        workspace.Towers.ToDM.Obby["Layer 4 (Button Challenges)"]:GetChildren()[11],
        workspace.Towers.ToDM.Obby["Layer 4 (Button Challenges)"]:GetChildren()[12],
        workspace.Towers.ToDM.Obby["Layer 4 (Button Challenges)"]:GetChildren()[18],
        workspace.Towers.ToDM.Obby["Layer 4 (Button Challenges)"]:GetChildren()[19],
        workspace.ClientParts.ClientSidedObjects:GetChildren()[1]:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[39],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[159],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms["Button Activated Rope Swing Platform"]:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Layer 4 (Button Challenges)"]:GetChildren()[27],
        workspace.Towers.ToDM.Obby["Layer 4 (Button Challenges)"]:GetChildren()[34],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[43],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[44],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[45],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[46],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[47],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[48],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[49],
        workspace.ClientParts.ClientSidedObjects:GetChildren()[23]:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[50],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[51],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[52],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[53],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[54],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[55],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[56],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[57],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[58],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[59],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[60],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[61],
        workspace.Towers.ToDM.Obby["Layer 4 (Button Challenges)"]:GetChildren()[47],
        workspace.Towers.ToDM.Obby["Layer 4 (Button Challenges)"]:GetChildren()[54],
        workspace.Towers.ToDM.Obby["Layer 4 (Button Challenges)"]:GetChildren()[55],
        workspace.Towers.ToDM.Obby["Layer 4 (Button Challenges)"]:GetChildren()[58],
        workspace.Towers.ToDM.Obby["Layer 4 (Button Challenges)"]:GetChildren()[77],
        workspace.ClientParts.ClientSidedObjects:GetChildren()[24]:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[63],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[64],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[65],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[66],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[67],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[68],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[161],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[151],
        workspace.Towers.ToDM.Obby["Layer 4 (Button Challenges)"]:GetChildren()[68],
        workspace.Towers.ToDM.Obby["Layer 4 (Button Challenges)"]:GetChildren()[74],
        workspace.ClientParts.ClientSidedObjects.KillBricks:GetChildren()[4],
        workspace.ClientParts.ClientSidedObjects:GetChildren()[22]:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[69],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[70],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[71],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[72],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[73],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[78],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[79],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[80],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[76],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[74],
        workspace.ClientParts.ClientSidedObjects:GetChildren()[20]:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[77],
        workspace.Towers.ToDM.Obby["Layer 4 (Button Challenges)"]:GetChildren()[95],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]["Floor and Ceiling (3)"]:GetChildren()[6],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[3]:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[3]:GetChildren()[2],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[15]:GetChildren()[4],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[15]:GetChildren()[3],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[4]:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[4]:GetChildren()[2],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[4]:GetChildren()[3],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[11]:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[11]:GetChildren()[2],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[11]:GetChildren()[3],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[12]:GetChildren()[4],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[2]:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[2]:GetChildren()[4],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[10]:GetChildren()[2],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[10]:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects.KillBricks:GetChildren()[6],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[5]:GetChildren()[3],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[5]:GetChildren()[4],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[6]:GetChildren()[2],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[6]:GetChildren()[3],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[6]:GetChildren()[4],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[7]:GetChildren()[2],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[7]:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[7]:GetChildren()[4],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[18],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[21],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[48],
        workspace.ClientParts.ClientSidedObjects:GetChildren()[17]:GetChildren()[3]:GetChildren()[2],
        workspace.ClientParts.ClientSidedObjects:GetChildren()[17]:GetChildren()[3]:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[22],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[23],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[24],
        workspace.ClientParts.ClientSidedObjects:GetChildren()[15]:GetChildren()[3]:GetChildren()[2],
        workspace.ClientParts.ClientSidedObjects:GetChildren()[15]:GetChildren()[3]:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[25],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[26],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[27],
        workspace.ClientParts.ClientSidedObjects:GetChildren()[18]:GetChildren()[3]:GetChildren()[2],
        workspace.ClientParts.ClientSidedObjects:GetChildren()[18]:GetChildren()[3]:GetChildren()[1],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[28],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[29],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[33],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[37],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[36],
        workspace.Towers.ToDM.Obby["Layer 3 (Magma Cave)"]:GetChildren()[39],
        workspace.Towers.ToDM.Obby["Layer 2"]:GetChildren()[5],
        workspace.Towers.ToDM.Obby["Layer 2"]:GetChildren()[6],
        workspace.Towers.ToDM.Obby["Layer 2"]:GetChildren()[7],
        workspace.Towers.ToDM.Obby["Layer 2"]:GetChildren()[11],
        workspace.Towers.ToDM.Obby["Layer 2"]:GetChildren()[56],
        workspace.Towers.ToDM.Obby["Layer 2"]:GetChildren()[19],
        workspace.Towers.ToDM.Obby["Layer 2"]:GetChildren()[27],
        workspace.Towers.ToDM.Obby["Layer 2"]:GetChildren()[33],
        workspace.Towers.ToDM.Obby["Layer 2"]:GetChildren()[39],
        workspace.Towers.ToDM.Obby["Layer 2"]:GetChildren()[62],
        workspace.Towers.ToDM.Obby["Layer 2"]:GetChildren()[53],
        workspace.Towers.ToDM.Obby["Layer 2"]:GetChildren()[55],
        workspace.Towers.ToDM.Obby["Layer 2"]:GetChildren()[54],
        workspace.Towers.ToDM.Obby["Layer 2"]:GetChildren()[13],
        workspace.Towers.ToDM.Obby["Layer 2"]:GetChildren()[63],
        workspace.ClientParts.ClientSidedObjects:GetChildren()[16]:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[94],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[100],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[99],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms["Button Activated Spinning Platform"].ButtonActivatedPlatform,
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[96],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[98],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[95],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[92],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[18],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[5],
        workspace.Towers.ToDM.Obby["Layer 2"]:GetChildren()[60],
        workspace.ClientParts.ClientSidedObjects:GetChildren()[21]:GetChildren()[1],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[81],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[86],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[87],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[88],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[119],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[120],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[126],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[109],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[125],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[124],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[123],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[110],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[131],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[134],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[133],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[135],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[132],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[136],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[140],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[111],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[152],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[113],
        workspace.ClientParts.ClientSidedObjects.ButtonPlatforms:GetChildren()[115],
        workspace.Towers.ToDM.WinPad
    }
end
