return function()
    return {
        workspace.Towers.ToA.Obby:GetChildren()[14], --F1
        workspace.Towers.ToA.Obby:GetChildren()[12],
        workspace.Towers.ToA.Obby:GetChildren()[59],
        workspace.Towers.ToA.Obby:GetChildren()[60],
        workspace.ClientParts.DistanceCulling:GetChildren()[13].Platform,
        workspace.Towers.ToA.Obby:GetChildren()[63],
        workspace.Towers.ToA.Obby:GetChildren()[62],
        workspace.Towers.ToA.Obby:GetChildren()[68],
        workspace.Towers.ToA.Obby:GetChildren()[71],
        workspace.Towers.ToA.Obby:GetChildren()[69],
        workspace.Towers.ToA.Obby:GetChildren()[67],
        workspace.Towers.ToA.Obby:GetChildren()[77],
        workspace.Towers.ToA.Obby:GetChildren()[75],
        workspace.Towers.ToA.Obby:GetChildren()[80],
        workspace.Towers.ToA.Obby:GetChildren()[84],
        workspace.ClientParts.DistanceCulling:GetChildren()[10].Platform,
        workspace.ClientParts.DistanceCulling:GetChildren()[11].Platform,
        workspace.Towers.ToA.Obby:GetChildren()[90],
        workspace.Towers.ToA.Obby:GetChildren()[66],
        workspace.ClientParts:GetChildren()[79],
        workspace.ClientParts:GetChildren()[80],
        workspace.Towers.ToA.Obby:GetChildren()[97],
        workspace.Towers.ToA.Obby:GetChildren()[92],
        workspace.Towers.ToA.Obby:GetChildren()[98],
        workspace.Towers.ToA.Obby:GetChildren()[93],
        workspace.Towers.ToA.Obby:GetChildren()[91],
        workspace.Towers.ToA.Obby:GetChildren()[100],
        workspace.Towers.ToA.Obby:GetChildren()[101],
        workspace.Towers.ToA.Obby:GetChildren()[99],
        workspace.Towers.ToA.Obby:GetChildren()[111],
        workspace.Towers.ToA.Obby:GetChildren()[112],
        workspace.ClientParts:GetChildren()[81],
        workspace.ClientParts:GetChildren()[82],
        workspace.ClientParts:GetChildren()[83],
        workspace.Towers.ToA.Obby:GetChildren()[105],
        workspace.Towers.ToA.Obby:GetChildren()[113],
        workspace.Towers.ToA.Obby:GetChildren()[115],
        workspace.Towers.ToA.Obby:GetChildren()[116],
        workspace.Towers.ToA.Obby:GetChildren()[120],
        workspace.ClientParts.DistanceCulling:GetChildren()[14].Platform,
        workspace.ClientParts.DistanceCulling:GetChildren()[15].Platform,
        workspace.ClientParts:GetChildren()[84],
        workspace.Towers.ToA.Obby:GetChildren()[121],
        workspace.Towers.ToA.Obby:GetChildren()[122],
        workspace.Towers.ToA.Obby:GetChildren()[124],
        workspace.Towers.ToA.Obby:GetChildren()[128],
        workspace.Towers.ToA.Obby:GetChildren()[129],
        workspace.Towers.ToA.Obby:GetChildren()[130],
        workspace.Towers.ToA.Obby:GetChildren()[131],
        workspace.Towers.ToA.Obby:GetChildren()[72],
        workspace.Towers.ToA.Obby:GetChildren()[20],
        workspace.Towers.ToA.Obby:GetChildren()[132],
        workspace.Towers.ToA.Obby:GetChildren()[133],
        workspace.ClientParts.DistanceCulling:GetChildren()[17].Platform,
        workspace.Towers.ToA.Obby:GetChildren()[138],
        workspace.Towers.ToA.Obby:GetChildren()[140],
        workspace.Towers.ToA.Obby:GetChildren()[155],
        workspace.Towers.ToA.Obby:GetChildren()[153],
        workspace.Towers.ToA.Obby:GetChildren()[143], --F2
        workspace.Towers.ToA.Obby:GetChildren()[168],
        workspace.Towers.ToA.Obby:GetChildren()[149],
        workspace.Towers.ToA.Obby:GetChildren()[169],
        workspace.Towers.ToA.Obby:GetChildren()[170],
        workspace.Towers.ToA.Obby:GetChildren()[171],
        workspace.Towers.ToA.Obby:GetChildren()[174],
        workspace.Towers.ToA.Obby:GetChildren()[172],
        workspace.Towers.ToA.Obby:GetChildren()[176],
        workspace.Towers.ToA.Obby:GetChildren()[177],
        workspace.Towers.ToA.Obby:GetChildren()[179],
        workspace.ClientParts:GetChildren()[85],
        workspace.ClientParts:GetChildren()[86],
        workspace.Towers.ToA.Obby:GetChildren()[187],
        workspace.Towers.ToA.Obby:GetChildren()[186],
        workspace.ClientParts.ParticleParts:GetChildren()[11],
        workspace.Towers.ToA.Obby:GetChildren()[1516],
        workspace.ClientParts.ParticleParts.Part,
        workspace.ClientParts["Rainbow Button 1"].Button.ButtonPart,
        workspace.ClientParts.ParticleParts["Rainbow Button 1"]:GetChildren()[10],
        workspace.ClientParts.ParticleParts["Rainbow Button 1"]:GetChildren()[7],
        workspace.ClientParts.ParticleParts["Rainbow Button 1"]:GetChildren()[4],
        workspace.ClientParts.ParticleParts["Rainbow Button 1"]:GetChildren()[3],
        workspace.ClientParts.ParticleParts["Rainbow Button 1"].Part,
        workspace.ClientParts.ParticleParts["Rainbow Button 1"]:GetChildren()[14],
        workspace.Towers.ToA.Obby:GetChildren()[206],
        workspace.Towers.ToA.Obby:GetChildren()[207],
        workspace.Towers.ToA.Obby:GetChildren()[210],
        workspace.ClientParts.DistanceCulling:GetChildren()[21].Parts:GetChildren()[2],
        workspace.Towers.ToA.Obby:GetChildren()[213],
        workspace.Towers.ToA.Obby:GetChildren()[215],
        workspace.Towers.ToA.Obby:GetChildren()[214],
        workspace.Towers.ToA.Obby:GetChildren()[54],
        workspace.Towers.ToA.Obby:GetChildren()[216],
        workspace.Towers.ToA.Obby:GetChildren()[218],
        workspace.Towers.ToA.Obby:GetChildren()[219],
        workspace.ClientParts.DistanceCulling:GetChildren()[23].Platform,
        workspace.ClientParts:GetChildren()[89],
        workspace.ClientParts:GetChildren()[90],
        workspace.ClientParts:GetChildren()[118],
        workspace.Towers.ToA.Obby:GetChildren()[223],
        workspace.Towers.ToA.Obby:GetChildren()[235],
        workspace.Towers.ToA.Obby:GetChildren()[230],
        workspace.Towers.ToA.Obby:GetChildren()[1522],
        workspace.Towers.ToA.Obby:GetChildren()[239],
        workspace.Towers.ToA.Obby:GetChildren()[240],
        workspace.ClientParts.DistanceCulling:GetChildren()[24].Platform,
        workspace.ClientParts.DistanceCulling:GetChildren()[24]:GetChildren()[2],
        workspace.ClientParts.DistanceCulling:GetChildren()[24]:GetChildren()[3],
        workspace.Towers.ToA.Obby:GetChildren()[241],
        workspace.Towers.ToA.Obby:GetChildren()[243],
        workspace.Towers.ToA.Obby:GetChildren()[246],
        workspace.Towers.ToA.Obby:GetChildren()[245],
        workspace.Towers.ToA.Obby:GetChildren()[248], --F3
        workspace.Towers.ToA.Obby:GetChildren()[247],
        workspace.Towers.ToA.Obby:GetChildren()[255],
        workspace.Towers.ToA.Obby:GetChildren()[254],
        workspace.Towers.ToA.Obby:GetChildren()[252],
        workspace.Towers.ToA.Obby:GetChildren()[253],
        workspace.Towers.ToA.Obby:GetChildren()[257],
        workspace.ClientParts.DistanceCulling:GetChildren()[26].Parts:GetChildren()[2],
        workspace.Towers.ToA.Obby:GetChildren()[258],
        workspace.Towers.ToA.Obby:GetChildren()[259],
        workspace.Towers.ToA.Obby:GetChildren()[261],
        workspace.Towers.ToA.Obby:GetChildren()[262],
        workspace.Towers.ToA.Obby:GetChildren()[263],
        workspace.Towers.ToA.Obby:GetChildren()[266],
        workspace.Towers.ToA.Obby:GetChildren()[268],
        workspace.Towers.ToA.Obby:GetChildren()[269],
        workspace.ClientParts:GetChildren()[93],
        workspace.ClientParts:GetChildren()[94],
        workspace.Towers.ToA.Obby:GetChildren()[275],
        workspace.Towers.ToA.Obby:GetChildren()[274],
        workspace.ClientParts:GetChildren()[27].Pushbox["Rope Swing Platform"].Platform,
        workspace.Towers.ToA.Obby:GetChildren()[280],
        workspace.Towers.ToA.Obby:GetChildren()[281],
        workspace.Towers.ToA.Obby:GetChildren()[282],
        workspace.Towers.ToA.Obby:GetChildren()[288],
        workspace.Towers.ToA.Obby:GetChildren()[277],
        workspace.Towers.ToA.Obby:GetChildren()[278],
        workspace.Towers.ToA.Obby:GetChildren()[283],
        workspace.Towers.ToA.Obby:GetChildren()[286],
        workspace.Towers.ToA.Obby:GetChildren()[289],
        workspace.Towers.ToA.Obby:GetChildren()[329],
        workspace.Towers.ToA.Obby:GetChildren()[284],
        workspace.Towers.ToA.Obby:GetChildren()[290],
        workspace.Towers.ToA.Obby:GetChildren()[307],
        workspace.Towers.ToA.Obby:GetChildren()[308],
        workspace.ClientParts:GetChildren()[29].Part,
        workspace.ClientParts:GetChildren()[29].Primary,
        workspace.ClientParts:GetChildren()[95],
        workspace.ClientParts:GetChildren()[96],
        workspace.Towers.ToA.Obby:GetChildren()[294],
        workspace.Towers.ToA.Obby:GetChildren()[316],
        workspace.Towers.ToA.Obby:GetChildren()[328],
        workspace.Towers.ToA.Obby:GetChildren()[325],
        workspace.Towers.ToA.Obby:GetChildren()[327],
        workspace.Towers.ToA.Obby:GetChildren()[326],
        workspace.Towers.ToA.Obby:GetChildren()[321],
        workspace.Towers.ToA.Obby:GetChildren()[324],
        workspace.Towers.ToA.Obby:GetChildren()[296],
        workspace.Towers.ToA.Obby:GetChildren()[319],
        workspace.Towers.ToA.Obby:GetChildren()[296],
        workspace.Towers.ToA.Obby:GetChildren()[299],
        workspace.Towers.ToA.Obby:GetChildren()[302],
        workspace.Towers.ToA.Obby:GetChildren()[298],
        workspace.ClientParts["Rainbow Button 2"].Button.Part,
        workspace.ClientParts["Rainbow Button 2"].Button.ButtonPart,
        workspace.ClientParts.ParticleParts["Rainbow Button 2"].Part,
        workspace.ClientParts.ParticleParts["Rainbow Button 2"]:GetChildren()[3],
        workspace.ClientParts.ParticleParts["Rainbow Button 2"]:GetChildren()[4],
        workspace.ClientParts.ParticleParts["Rainbow Button 2"]:GetChildren()[5],
        workspace.ClientParts.ParticleParts["Rainbow Button 2"]:GetChildren()[6],
        workspace.ClientParts.ParticleParts["Rainbow Button 2"]:GetChildren()[7],
        workspace.ClientParts:GetChildren()[97],
        workspace.ClientParts:GetChildren()[98],
        workspace.ClientParts:GetChildren()[99],
        workspace.Towers.ToA.Obby:GetChildren()[352],
        workspace.Towers.ToA.Obby:GetChildren()[354],
        workspace.Towers.ToA.Obby:GetChildren()[355],
        workspace.Towers.ToA.Obby:GetChildren()[370],
        workspace.Towers.ToA.Obby:GetChildren()[356],
        workspace.Towers.ToA.Obby:GetChildren()[369],
        workspace.Towers.ToA.Obby:GetChildren()[357],
        workspace.Towers.ToA.Obby:GetChildren()[358],
        workspace.Towers.ToA.Obby:GetChildren()[360],
        workspace.Towers.ToA.Obby:GetChildren()[362],
        workspace.Towers.ToA.Obby:GetChildren()[364], --F4
        workspace.Towers.ToA.Obby:GetChildren()[342],
        workspace.ClientParts:GetChildren()[103],
        workspace.Towers.ToA.Obby:GetChildren()[335],
        workspace.Towers.ToA.Obby:GetChildren()[431],
        workspace.Towers.ToA.Obby:GetChildren()[429],
        workspace.Towers.ToA.Obby:GetChildren()[430],
        workspace.Towers.ToA.Obby:GetChildren()[427],
        workspace.Towers.ToA.Obby:GetChildren()[440],
        workspace.Towers.ToA.Obby:GetChildren()[441],
        workspace.ClientParts:GetChildren()[108],
        workspace.Towers.ToA.Obby:GetChildren()[426],
        workspace.Towers.ToA.Obby:GetChildren()[423],
        workspace.Towers.ToA.Obby:GetChildren()[462],
        workspace.Towers.ToA.Obby:GetChildren()[464],
        workspace.Towers.ToA.Obby:GetChildren()[465],
        workspace.ClientParts:GetChildren()[113],
        workspace.Towers.ToA.Obby:GetChildren()[477],
        workspace.Towers.ToA.Obby:GetChildren()[491],
        workspace.Towers.ToA.Obby:GetChildren()[474],
        workspace.ClientParts["Rainbow Button 3"].Button.ButtonPart,
        workspace.ClientParts.ParticleParts["Rainbow Button 3"].Part,
        workspace.ClientParts.ParticleParts["Rainbow Button 3"]:GetChildren()[6],
        workspace.ClientParts.ParticleParts["Rainbow Button 3"].PushboxSpawnButton.Pushbox["Rope Swing Platform"].Platform,
        workspace.ClientParts.ParticleParts["Rainbow Button 3"]:GetChildren()[8],
        workspace.ClientParts.ParticleParts["Rainbow Button 3"]:GetChildren()[10],
        workspace.ClientParts.ParticleParts["Rainbow Button 3"]["Rope Swing Platform"].Platform,
        workspace.ClientParts.ParticleParts["Rainbow Button 3"]:GetChildren()[3].Platform,
        workspace.ClientParts:GetChildren()[116],
        workspace.ClientParts:GetChildren()[117],
        workspace.Towers.ToA.Obby:GetChildren()[502],
        workspace.Towers.ToA.Obby:GetChildren()[503],
        workspace.Towers.ToA.Obby:GetChildren()[508],
        workspace.Towers.ToA.Obby:GetChildren()[509],
        workspace.Towers.ToA.Obby:GetChildren()[526],
        workspace.Towers.ToA.Obby:GetChildren()[525],
        workspace.Towers.ToA.Obby:GetChildren()[524],
        workspace.Towers.ToA.Obby:GetChildren()[527],
        workspace.Towers.ToA.Obby:GetChildren()[530],
        workspace.Towers.ToA.Obby:GetChildren()[529],
        workspace.Towers.ToA.Obby:GetChildren()[1494],
        workspace.Towers.ToA.Obby:GetChildren()[510],
        workspace.Towers.ToA.Obby:GetChildren()[534],
        workspace.Towers.ToA.Obby:GetChildren()[532],
        workspace.Towers.ToA.Obby:GetChildren()[531],
        workspace.ClientParts.DistanceCulling:GetChildren()[27].Platform,
        workspace.ClientParts.DistanceCulling:GetChildren()[27]:GetChildren()[2],
        workspace.ClientParts.DistanceCulling:GetChildren()[27]:GetChildren()[6],
        workspace.ClientParts.DistanceCulling:GetChildren()[27]:GetChildren()[8],
        workspace.ClientParts.DistanceCulling:GetChildren()[27]:GetChildren()[9],
        workspace.ClientParts.DistanceCulling:GetChildren()[27]:GetChildren()[7],
        workspace.ClientParts.DistanceCulling:GetChildren()[27]:GetChildren()[3],
        workspace.Towers.ToA.Obby:GetChildren()[536], --F5
        workspace.Towers.ToA.Obby:GetChildren()[538],
        workspace.Towers.ToA.Obby:GetChildren()[543],
        workspace.Towers.ToA.Obby:GetChildren()[542],
        workspace.Towers.ToA.Obby:GetChildren()[548],
        workspace.ClientParts:GetChildren()[119],
        workspace.ClientParts:GetChildren()[92],
        workspace.ClientParts:GetChildren()[91],
        workspace.Towers.ToA.Obby:GetChildren()[551],
        workspace.Towers.ToA.Obby:GetChildren()[556],
        workspace.Towers.ToA.Obby:GetChildren()[553],
        workspace.ClientParts.DistanceCulling:GetChildren()[28].Parts.Part,
        workspace.Towers.ToA.Obby:GetChildren()[574],
        workspace.ClientParts.DistanceCulling:GetChildren()[28].Parts.Part,
        workspace.Towers.ToA.Obby:GetChildren()[578],
        workspace.Towers.ToA.Obby:GetChildren()[579],
        workspace.ClientParts:GetChildren()[57],
        workspace.ClientParts:GetChildren()[59],
        workspace.Towers.ToA.Obby:GetChildren()[583],
        workspace.Towers.ToA.Obby:GetChildren()[582],
        workspace.Towers.ToA.Obby:GetChildren()[592],
        workspace.Towers.ToA.Obby:GetChildren()[590],
        workspace.Towers.ToA.Obby:GetChildren()[591],
        workspace.Towers.ToA.Obby:GetChildren()[593],
        workspace.Towers.ToA.Obby:GetChildren()[594],
        workspace.Towers.ToA.Obby:GetChildren()[596],
        workspace.Towers.ToA.Obby:GetChildren()[597],
        workspace.ClientParts.DistanceCulling:GetChildren()[30].Platform,
        workspace.Towers.ToA.Obby:GetChildren()[600],
        workspace.Towers.ToA.Obby:GetChildren()[601],
        workspace.Towers.ToA.Obby:GetChildren()[606],
        workspace.Towers.ToA.Obby:GetChildren()[610],
        workspace.Towers.ToA.Obby:GetChildren()[613],
        workspace.Towers.ToA.Obby:GetChildren()[611],
        workspace.Towers.ToA.Obby:GetChildren()[614],
        workspace.Towers.ToA.Obby:GetChildren()[615],
        workspace.Towers.ToA.Obby:GetChildren()[612],
        workspace.Towers.ToA.Obby:GetChildren()[622],
        workspace.Towers.ToA.Obby:GetChildren()[620],
        workspace.Towers.ToA.Obby:GetChildren()[624],
        workspace.Towers.ToA.Obby:GetChildren()[623],
        workspace.Towers.ToA.Obby:GetChildren()[625],
        workspace.Towers.ToA.Obby:GetChildren()[626],
        workspace.Towers.ToA.Obby:GetChildren()[627],
        workspace.ClientParts:GetChildren()[121],
        workspace.ClientParts:GetChildren()[122],
        workspace.Towers.ToA.Obby:GetChildren()[628],
        workspace.Towers.ToA.Obby:GetChildren()[631],
        workspace.Towers.ToA.Obby:GetChildren()[630],
        workspace.ClientParts.DistanceCulling:GetChildren()[31].Platform,
        workspace.Towers.ToA.Obby:GetChildren()[634],
        workspace.Towers.ToA.Obby:GetChildren()[638],
        workspace.Towers.ToA.Obby:GetChildren()[640],
        workspace.Towers.ToA.Obby:GetChildren()[637],
        workspace.Towers.ToA.Obby:GetChildren()[639],
        workspace.Towers.ToA.Obby:GetChildren()[589],
        workspace.Towers.ToA.Obby:GetChildren()[641],
        workspace.Towers.ToA.Obby:GetChildren()[642],
        workspace.Towers.ToA.Obby:GetChildren()[643],
        workspace.Towers.ToA.Obby:GetChildren()[644],
        workspace.Towers.ToA.Obby:GetChildren()[539],
        workspace.ClientParts.DistanceCulling:GetChildren()[32].Platform,
        workspace.ClientParts.DistanceCulling:GetChildren()[34].Platform,
        workspace.ClientParts.DistanceCulling:GetChildren()[33].Platform,
        workspace.Towers.ToA.Obby:GetChildren()[645],
        workspace.Towers.ToA.Obby:GetChildren()[646],
        workspace.ClientParts["Rainbow Button 4"].Button.ButtonPart,
        workspace.Towers.ToA.Obby:GetChildren()[646],
        workspace.Towers.ToA.Obby:GetChildren()[645],
        workspace.ClientParts.ParticleParts["Rainbow Button 4"]:GetChildren()[5],
        workspace.ClientParts.ParticleParts["Rainbow Button 4"].Part,
        workspace.ClientParts.ParticleParts["Rainbow Button 4"]:GetChildren()[4],
        workspace.ClientParts.ParticleParts["Rainbow Button 4"]["Rope Swing Platform"].Platform,
        workspace.ClientParts.ParticleParts["Rainbow Button 4"]:GetChildren()[2].Platform,
        workspace.ClientParts.ParticleParts["Rainbow Button 3"]:GetChildren()[4].Pushbox["Rope Swing Platform"].Platform,
        workspace.Towers.ToA.Obby:GetChildren()[651],
        workspace.Towers.ToA.Obby:GetChildren()[653],
        workspace.Towers.ToA.Obby:GetChildren()[661],
        workspace.Towers.ToA.Obby:GetChildren()[660],
        workspace.Towers.ToA.Obby:GetChildren()[659],
        workspace.Towers.ToA.Obby:GetChildren()[663],
        workspace.Towers.ToA.Obby:GetChildren()[668],
        workspace.Towers.ToA.Obby:GetChildren()[667],
        workspace.Towers.ToA.Obby:GetChildren()[669],
        workspace.Towers.ToA.Obby:GetChildren()[670],
        workspace.ClientParts.DistanceCulling:GetChildren()[35].Platform,
        workspace.ClientParts:GetChildren()[39].Pushbox["Rope Swing Platform"].Platform,
        workspace.ClientParts:GetChildren()[124],
        workspace.ClientParts:GetChildren()[125],
        workspace.Towers.ToA.Obby:GetChildren()[683],
        workspace.Towers.ToA.Obby:GetChildren()[685],
        workspace.Towers.ToA.Obby:GetChildren()[698],
        workspace.Towers.ToA.Obby:GetChildren()[699],
        workspace.Towers.ToA.Obby:GetChildren()[691],
        workspace.Towers.ToA.Obby:GetChildren()[695],
        workspace.Towers.ToA.Obby:GetChildren()[690], --F6
        workspace.Towers.ToA.Obby:GetChildren()[700],
        workspace.Towers.ToA.Obby:GetChildren()[701],
        workspace.Towers.ToA.Obby:GetChildren()[677],
        workspace.ClientParts:GetChildren()[40].Primary,
        workspace.Towers.ToA.Obby:GetChildren()[703],
        workspace.Towers.ToA.Obby:GetChildren()[702],
        workspace.Towers.ToA.Obby:GetChildren()[709],
        workspace.Towers.ToA.Obby:GetChildren()[715],
        workspace.Towers.ToA.Obby:GetChildren()[714],
        workspace.Towers.ToA.Obby:GetChildren()[716],
        workspace.Towers.ToA.Obby:GetChildren()[718],
        workspace.ClientParts:GetChildren()[126],
        workspace.ClientParts:GetChildren()[128],
        workspace.ClientParts:GetChildren()[126],
        workspace.ClientParts:GetChildren()[18],
        workspace.Towers.ToA.Obby:GetChildren()[1241],
        workspace.Towers.ToA.Obby:GetChildren()[762],
        workspace.Towers.ToA.Obby:GetChildren()[745],
        workspace.Towers.ToA.Obby:GetChildren()[760],
        workspace.Towers.ToA.Obby:GetChildren()[759],
        workspace.Towers.ToA.Obby:GetChildren()[758],
        workspace.Towers.ToA.Obby:GetChildren()[757],
        workspace.Towers.ToA.Obby:GetChildren()[756],
        workspace.Towers.ToA.Obby:GetChildren()[755],
        workspace.Towers.ToA.Obby:GetChildren()[754],
        workspace.Towers.ToA.Obby:GetChildren()[753],
        workspace.Towers.ToA.Obby:GetChildren()[752],
        workspace.Towers.ToA.Obby:GetChildren()[751],
        workspace.Towers.ToA.Obby:GetChildren()[750],
        workspace.Towers.ToA.Obby:GetChildren()[749],
        workspace.Towers.ToA.Obby:GetChildren()[748],
        workspace.Towers.ToA.Obby:GetChildren()[747],
        workspace.Towers.ToA.Obby:GetChildren()[746],
        workspace.Towers.ToA.Obby:GetChildren()[728],
        workspace.Towers.ToA.Obby:GetChildren()[765],
        workspace.Towers.ToA.Obby:GetChildren()[764],
        workspace.Towers.ToA.Obby:GetChildren()[767],
        workspace.Towers.ToA.Obby:GetChildren()[769],
        workspace.Towers.ToA.Obby:GetChildren()[768],
        workspace.Towers.ToA.Obby:GetChildren()[770],
        workspace.ClientParts:GetChildren()[49],
        workspace.ClientParts:GetChildren()[56],
        workspace.ClientParts:GetChildren()[43],
        workspace.ClientParts:GetChildren()[15],
        workspace.Towers.ToA.Obby:GetChildren()[786],
        workspace.Towers.ToA.Obby:GetChildren()[787],
        workspace.Towers.ToA.Obby:GetChildren()[788],
        workspace.Towers.ToA.Obby:GetChildren()[789],
        workspace.Towers.ToA.Obby:GetChildren()[790],
        workspace.Towers.ToA.Obby:GetChildren()[791],
        workspace.Towers.ToA.Obby:GetChildren()[792],
        workspace.Towers.ToA.Obby:GetChildren()[793],
        workspace.Towers.ToA.Obby:GetChildren()[794],
        workspace.Towers.ToA.Obby:GetChildren()[795],
        workspace.Towers.ToA.Obby:GetChildren()[796],
        workspace.Towers.ToA.Obby:GetChildren()[797],
        workspace.Towers.ToA.Obby:GetChildren()[785],
        workspace.Towers.ToA.Obby:GetChildren()[829],
        workspace.Towers.ToA.Obby:GetChildren()[833],
        workspace.Towers.ToA.Obby:GetChildren()[834],
        workspace.Towers.ToA.Obby:GetChildren()[835],
        workspace.ClientParts:GetChildren()[51],
        workspace.ClientParts:GetChildren()[47],
        workspace.Towers.ToA.Obby:GetChildren()[785],
        workspace.Towers.ToA.Obby:GetChildren()[798],
        workspace.Towers.ToA.Obby:GetChildren()[799],
        workspace.Towers.ToA.Obby:GetChildren()[800],
        workspace.Towers.ToA.Obby:GetChildren()[801],
        workspace.Towers.ToA.Obby:GetChildren()[802],
        workspace.Towers.ToA.Obby:GetChildren()[803],
        workspace.Towers.ToA.Obby:GetChildren()[804],
        workspace.Towers.ToA.Obby:GetChildren()[805],
        workspace.Towers.ToA.Obby:GetChildren()[806],
        workspace.Towers.ToA.Obby:GetChildren()[807],
        workspace.Towers.ToA.Obby:GetChildren()[808],
        workspace.Towers.ToA.Obby:GetChildren()[812],
        workspace.Towers.ToA.Obby:GetChildren()[825],
        workspace.Towers.ToA.Obby:GetChildren()[1243],
        workspace.Towers.ToA.Obby:GetChildren()[849],
        workspace.Towers.ToA.Obby:GetChildren()[850],
        workspace.Towers.ToA.Obby:GetChildren()[851],
        workspace.Towers.ToA.Obby:GetChildren()[855],
        workspace.ClientParts:GetChildren()[41].Primary,
        workspace.Towers.ToA.Obby:GetChildren()[858],
        workspace.Towers.ToA.Obby:GetChildren()[856],
        workspace.Towers.ToA.Obby:GetChildren()[857],
        workspace.ClientParts:GetChildren()[48],
        workspace.ClientParts:GetChildren()[53],
        workspace.Towers.ToA.Obby:GetChildren()[859],
        workspace.Towers.ToA.Obby:GetChildren()[876],
        workspace.Towers.ToA.Obby:GetChildren()[863],
        workspace.Towers.ToA.Obby:GetChildren()[867],
        workspace.Towers.ToA.Obby:GetChildren()[872], --F7
        workspace.Towers.ToA.Obby:GetChildren()[864],
        workspace.Towers.ToA.Obby:GetChildren()[886],
        workspace.ClientParts.DistanceCulling:GetChildren()[36].Platform,
        workspace.Towers.ToA.Obby:GetChildren()[891],
        workspace.Towers.ToA.Obby:GetChildren()[893],
        workspace.Towers.ToA.Obby:GetChildren()[890],
        workspace.Towers.ToA.Obby:GetChildren()[889],
        workspace.Towers.ToA.Obby:GetChildren()[888],
        workspace.Towers.ToA.Obby:GetChildren()[887],
        workspace.ClientParts:GetChildren()[54],
        workspace.ClientParts:GetChildren()[55],
        workspace.Towers.ToA.Obby:GetChildren()[956],
        workspace.Towers.ToA.Obby:GetChildren()[955],
        workspace.Towers.ToA.Obby:GetChildren()[895],
        workspace.Towers.ToA.Obby:GetChildren()[959],
        workspace.Towers.ToA.Obby:GetChildren()[958],
        workspace.Towers.ToA.Obby:GetChildren()[960],
        workspace.Towers.ToA.Obby:GetChildren()[961],
        workspace.Towers.ToA.Obby:GetChildren()[962],
        workspace.Towers.ToA.Obby:GetChildren()[1244],
        workspace.Towers.ToA.Obby:GetChildren()[900],
        workspace.Towers.ToA.Obby:GetChildren()[898],
        workspace.Towers.ToA.Obby:GetChildren()[968],
        workspace.Towers.ToA.Obby:GetChildren()[969],
        workspace.ClientParts:GetChildren()[123],
        workspace.Towers.ToA.Obby:GetChildren()[996],
        workspace.Towers.ToA.Obby:GetChildren()[994],
        workspace.Towers.ToA.Obby:GetChildren()[995],
        workspace.Towers.ToA.Obby:GetChildren()[997],
        workspace.Towers.ToA.Obby:GetChildren()[998],
        workspace.ClientParts:GetChildren()[20].Pushbox["Rope Swing Platform"].Platform,
        workspace.Towers.ToA.Obby:GetChildren()[1006],
        workspace.Towers.ToA.Obby:GetChildren()[1005],
        workspace.Towers.ToA.Obby:GetChildren()[1007],
        workspace.Towers.ToA.Obby:GetChildren()[1008],
        workspace.Towers.ToA.Obby:GetChildren()[1245],
        workspace.Towers.ToA.Obby:GetChildren()[877],
        workspace.ClientParts["Rainbow Button 5"].Button.ButtonPart,
        workspace.ClientParts.ParticleParts["Rainbow Button 5"]:GetChildren()[7],
        workspace.ClientParts.ParticleParts["Rainbow Button 5"]:GetChildren()[10],
        workspace.ClientParts.ParticleParts["Rainbow Button 5"]:GetChildren()[11],
        workspace.ClientParts.ParticleParts["Rainbow Button 5"]:GetChildren()[5],
        workspace.ClientParts.ParticleParts["Rainbow Button 5"]:GetChildren()[6],
        workspace.Towers.ToA.Obby:GetChildren()[901],
        workspace.ClientParts.ParticleParts["Rainbow Button 5"]:GetChildren()[4],
        workspace.ClientParts.ParticleParts["Rainbow Button 5"]:GetChildren()[3],
        workspace.Towers.ToA.Obby:GetChildren()[973],
        workspace.Towers.ToA.Obby:GetChildren()[971],
        workspace.Towers.ToA.Obby:GetChildren()[903],
        workspace.Towers.ToA.Obby:GetChildren()[989],
        workspace.Towers.ToA.Obby:GetChildren()[990],
        workspace.Towers.ToA.Obby:GetChildren()[987],
        workspace.ClientParts.ParticleParts["Rainbow Button 5"]["Rope Swing Platform"].Platform,
        workspace.ClientParts.ParticleParts["Rainbow Button 5"]:GetChildren()[8],
        workspace.ClientParts.ParticleParts["Rainbow Button 5"]:GetChildren()[9],
        workspace.ClientParts.ParticleParts["Rainbow Button 5"]:GetChildren()[13],
        workspace.ClientParts.ParticleParts["Rainbow Button 5"]:GetChildren()[14],
        workspace.Towers.ToA.Obby:GetChildren()[910],
        workspace.Towers.ToA.Obby:GetChildren()[1015],
        workspace.Towers.ToA.Obby:GetChildren()[1014],
        workspace.Towers.ToA.Obby:GetChildren()[1012],
        workspace.Towers.ToA.Obby:GetChildren()[1011],
        workspace.Towers.ToA.Obby:GetChildren()[1010],
        workspace.Towers.ToA.Obby:GetChildren()[1009],
        workspace.Towers.ToA.Obby:GetChildren()[1016],
        workspace.Towers.ToA.Obby:GetChildren()[1017], --F8
        workspace.Towers.ToA.Obby:GetChildren()[908],
        workspace.ClientParts:GetChildren()[75],
        workspace.ClientParts:GetChildren()[71],
        workspace.Towers.ToA.Obby:GetChildren()[1021],
        workspace.Towers.ToA.Obby:GetChildren()[1020],
        workspace.Towers.ToA.Obby:GetChildren()[1025],
        workspace.Towers.ToA.Obby:GetChildren()[1027],
        workspace.ClientParts.DistanceCulling:GetChildren()[6].Platform,
        workspace.Towers.ToA.Obby:GetChildren()[1029],
        workspace.Towers.ToA.Obby:GetChildren()[1422],
        workspace.Towers.ToA.Obby:GetChildren()[1030],
        workspace.Towers.ToA.Obby:GetChildren()[1035],
        workspace.Towers.ToA.Obby:GetChildren()[1033],
        workspace.Towers.ToA.Obby:GetChildren()[1038],
        workspace.Towers.ToA.Obby:GetChildren()[1036],
        workspace.Towers.ToA.Obby:GetChildren()[1043],
        workspace.Towers.ToA.Obby:GetChildren()[1042],
        workspace.Towers.ToA.Obby:GetChildren()[1040],
        workspace.Towers.ToA.Obby:GetChildren()[1031],
        workspace.Towers.ToA.Obby:GetChildren()[1048],
        workspace.Towers.ToA.Obby:GetChildren()[1047],
        workspace.Towers.ToA.Obby:GetChildren()[1049],
        workspace.Towers.ToA.Obby:GetChildren()[1051],
        workspace.Towers.ToA.Obby:GetChildren()[1060],
        workspace.Towers.ToA.Obby:GetChildren()[1061],
        workspace.Towers.ToA.Obby:GetChildren()[1058],
        workspace.Towers.ToA.Obby:GetChildren()[1054],
        workspace.Towers.ToA.Obby:GetChildren()[1053],
        workspace.Towers.ToA.Obby:GetChildren()[1065],
        workspace.Towers.ToA.Obby:GetChildren()[1070],
        workspace.Towers.ToA.Obby:GetChildren()[1068],
        workspace.ClientParts:GetChildren()[73],
        workspace.ClientParts:GetChildren()[60],
        workspace.ClientParts:GetChildren()[61],
        workspace.Towers.ToA.Obby:GetChildren()[1089],
        workspace.Towers.ToA.Obby:GetChildren()[1087],
        workspace.Towers.ToA.Obby:GetChildren()[1088],
        workspace.Towers.ToA.Obby:GetChildren()[1078],
        workspace.Towers.ToA.Obby:GetChildren()[1083],
        workspace.ClientParts["Pushing Platform"].Primary,
        workspace.Towers.ToA.Obby:GetChildren()[1093],
        workspace.Towers.ToA.Obby:GetChildren()[1114],
        workspace.Towers.ToA.Obby:GetChildren()[1111],
        workspace.Towers.ToA.Obby:GetChildren()[1117],
        workspace.Towers.ToA.Obby:GetChildren()[1115],
        workspace.Towers.ToA.Obby:GetChildren()[1121],
        workspace.Towers.ToA.Obby:GetChildren()[1122],
        workspace.Towers.ToA.Obby:GetChildren()[1123],
        workspace.Towers.ToA.Obby:GetChildren()[1094],
        workspace.Towers.ToA.Obby:GetChildren()[1126],
        workspace.Towers.ToA.Obby:GetChildren()[1127],
        workspace.Towers.ToA.Obby:GetChildren()[1132],
        workspace.Towers.ToA.Obby:GetChildren()[1137],
        workspace.Towers.ToA.Obby:GetChildren()[1134],
        workspace.Towers.ToA.Obby:GetChildren()[1141],
        workspace.Towers.ToA.Obby:GetChildren()[1140],
        workspace.Towers.ToA.Obby:GetChildren()[1145],
        workspace.Towers.ToA.Obby:GetChildren()[1444],
        workspace.Towers.ToA.Obby:GetChildren()[1150],
        workspace.Towers.ToA.Obby:GetChildren()[1148], --F9
        workspace.Towers.ToA.Obby:GetChildren()[1128],
        workspace.Towers.ToA.Obby:GetChildren()[1157],
        workspace.Towers.ToA.Obby:GetChildren()[1159],
        workspace.Towers.ToA.Obby:GetChildren()[1162],
        workspace.Towers.ToA.Obby:GetChildren()[1165],
        workspace.Towers.ToA.Obby:GetChildren()[1164],
        workspace.Towers.ToA.Obby:GetChildren()[1163],
        workspace.Towers.ToA.Obby:GetChildren()[1169],
        workspace.Towers.ToA.Obby:GetChildren()[1168],
        workspace.Towers.ToA.Obby:GetChildren()[1178],
        workspace.Towers.ToA.Obby:GetChildren()[1177],
        workspace.ClientParts:GetChildren()[12].Primary,
        workspace.Towers.ToA.Obby:GetChildren()[1099],
        workspace.Towers.ToA.Obby:GetChildren()[1183],
        workspace.Towers.ToA.Obby:GetChildren()[1182],
        workspace.Towers.ToA.Obby:GetChildren()[1223],
        workspace.Towers.ToA.Obby:GetChildren()[1185],
        workspace.Towers.ToA.Obby:GetChildren()[1184],
        workspace.Towers.ToA.Obby:GetChildren()[1186],
        workspace.Towers.ToA.Obby:GetChildren()[1187],
        workspace.Towers.ToA.Obby:GetChildren()[1100],
        workspace.Towers.ToA.Obby:GetChildren()[1192],
        workspace.Towers.ToA.Obby:GetChildren()[1191],
        workspace.Towers.ToA.Obby:GetChildren()[1099],
        workspace.Towers.ToA.Obby:GetChildren()[1100],
        workspace.Towers.ToA.Obby:GetChildren()[1195],
        workspace.Towers.ToA.Obby:GetChildren()[1197],
        workspace.Towers.ToA.Obby:GetChildren()[1194],
        workspace.Towers.ToA.Obby:GetChildren()[1196],
        workspace.Towers.ToA.Obby:GetChildren()[1100],
        workspace.Towers.ToA.Obby:GetChildren()[1202],
        workspace.Towers.ToA.Obby:GetChildren()[1203],
        workspace.Towers.ToA.Obby:GetChildren()[1102],
        workspace.Towers.ToA.Obby:GetChildren()[1171],
        workspace.Towers.ToA.Obby:GetChildren()[1170],
        workspace.Towers.ToA.Obby:GetChildren()[1101],
        workspace.Towers.ToA.Obby:GetChildren()[1206],
        workspace.Towers.ToA.Obby:GetChildren()[1207],
        workspace.Towers.ToA.Obby:GetChildren()[1105],
        workspace.ClientParts:GetChildren()[78],
        workspace.Towers.ToA.Obby:GetChildren()[1103],
        workspace.ClientParts:GetChildren()[77],
        workspace.Towers.ToA.Obby:GetChildren()[1210],
        workspace.Towers.ToA.Obby:GetChildren()[1209],
        workspace.Towers.ToA.Obby:GetChildren()[1208],
        workspace.Towers.ToA.Obby:GetChildren()[1104],
        workspace.Towers.ToA.Obby:GetChildren()[1213],
        workspace.Towers.ToA.Obby:GetChildren()[1214],
        workspace.Towers.ToA.Obby:GetChildren()[1217],
        workspace.Towers.ToA.Obby:GetChildren()[1218],
        workspace.Towers.ToA.Obby:GetChildren()[1216],
        workspace.Towers.ToA.Obby:GetChildren()[1106],
        workspace.Towers.ToA.Obby:GetChildren()[1220],
        workspace.ClientParts:GetChildren()[35].Primary,
        workspace.ClientParts:GetChildren()[120],
        workspace.Towers.ToA.Obby:GetChildren()[1224], --F10
        workspace.Towers.ToA.Obby:GetChildren()[1225],
        workspace.Towers.ToA.Obby:GetChildren()[1229],
        workspace.Towers.ToA.Obby:GetChildren()[1228],
        workspace.Towers.ToA.Obby:GetChildren()[1282],
        workspace.Towers.ToA.Obby:GetChildren()[1226],
        workspace.ClientParts.KillBricks:GetChildren()[334],
        workspace.ClientParts.KillBricks:GetChildren()[331],
        workspace.ClientParts.KillBricks:GetChildren()[333],
        workspace.ClientParts.KillBricks:GetChildren()[332],
        workspace.ClientParts.DistanceCulling:GetChildren()[8].Platform,
        workspace.ClientParts["Rainbow Button 6"].Button.ButtonPart,
        workspace.ClientParts.ParticleParts["Rainbow Button 6"]:GetChildren()[8],
        workspace.ClientParts.ParticleParts["Rainbow Button 6"]:GetChildren()[7],
        workspace.ClientParts.DistanceCulling:GetChildren()[8].Platform,
        workspace.ClientParts.ParticleParts["Rainbow Button 6"].Part,
        workspace.ClientParts.ParticleParts["Rainbow Button 6"]:GetChildren()[2],
        workspace.ClientParts.ParticleParts["Rainbow Button 6"]:GetChildren()[3],
        workspace.ClientParts.ParticleParts["Rainbow Button 6"]:GetChildren()[4],
        workspace.ClientParts.ParticleParts["Rainbow Button 6"]:GetChildren()[5],
        workspace.ClientParts.ParticleParts["Rainbow Button 6"]:GetChildren()[6],
        workspace.ClientParts:GetChildren()[68],
        workspace.ClientParts:GetChildren()[76],
        workspace.Towers.ToA.Obby:GetChildren()[1361],
        workspace.ClientParts.KillBricks:GetChildren()[357],
        workspace.ClientParts.KillBricks:GetChildren()[358],
        workspace.ClientParts.KillBricks:GetChildren()[6],
        workspace.ClientParts.KillBricks:GetChildren()[5],
        workspace.ClientParts.KillBricks:GetChildren()[4],
        workspace.Towers.ToA.Obby:GetChildren()[1398],
        workspace.Towers.ToA.WinPad
    }
end
