return function()
    return {
        workspace.Towers.ToTS.Obby:GetChildren()[137],
        workspace.Towers.ToTS.Obby:GetChildren()[155],
        workspace.Towers.ToTS.Obby:GetChildren()[156],
        workspace.Towers.ToTS.Obby:GetChildren()[147],
        workspace.Towers.ToTS.Obby:GetChildren()[473],
        workspace.Towers.ToTS.Obby:GetChildren()[441],
        workspace.Towers.ToTS.Obby:GetChildren()[411],
        workspace.Towers.ToTS.Obby:GetChildren()[190],
        workspace.Towers.ToTS.Obby:GetChildren()[532],
        workspace.Towers.ToTS.Obby:GetChildren()[422],
        workspace.Towers.ToTS.Obby:GetChildren()[423],
        workspace.Towers.ToTS.Obby:GetChildren()[531],
        workspace.Towers.ToTS.Obby:GetChildren()[426],
        workspace.Towers.ToTS.Obby:GetChildren()[425],
        workspace.Towers.ToTS.Obby:GetChildren()[409],
        workspace.Towers.ToTS.Obby:GetChildren()[420],
        workspace.Towers.ToTS.Obby:GetChildren()[416],
        workspace.Towers.ToTS.Obby:GetChildren()[415],
        workspace.Towers.ToTS.Obby:GetChildren()[418],
        workspace.Towers.ToTS.Obby:GetChildren()[414],
        workspace.Towers.ToTS.Obby:GetChildren()[424],
        workspace.Towers.ToTS.Obby:GetChildren()[533],
        workspace.Towers.ToTS.Obby:GetChildren()[511],
        workspace.Towers.ToTS.Obby:GetChildren()[547],
        workspace.Towers.ToTS.Obby:GetChildren()[555],
        workspace.Towers.ToTS.Obby:GetChildren()[546],
        workspace.Towers.ToTS.Obby:GetChildren()[510],
        workspace.Towers.ToTS.Obby:GetChildren()[526],
        workspace.Towers.ToTS.Obby:GetChildren()[514],
        workspace.Towers.ToTS.Obby:GetChildren()[539],
        workspace.Towers.ToTS.Obby:GetChildren()[553],
        workspace.Towers.ToTS.Obby:GetChildren()[520],
        workspace.Towers.ToTS.Obby:GetChildren()[500], --F2
        workspace.Towers.ToTS.Obby:GetChildren()[208],
        workspace.Towers.ToTS.Obby:GetChildren()[529],
        workspace.Towers.ToTS.Obby:GetChildren()[505],
        workspace.Towers.ToTS.Obby:GetChildren()[475],
        workspace.Towers.ToTS.Obby:GetChildren()[174],
        workspace.Towers.ToTS.Obby:GetChildren()[495],
        workspace.Towers.ToTS.Obby:GetChildren()[486],
        workspace.Towers.ToTS.Obby:GetChildren()[302],
        workspace.Towers.ToTS.Obby:GetChildren()[462],
        workspace.Towers.ToTS.Obby:GetChildren()[297],
        workspace.Towers.ToTS.Obby:GetChildren()[301],
        workspace.Towers.ToTS.Obby:GetChildren()[431],
        workspace.Towers.ToTS.Obby:GetChildren()[284],
        workspace.Towers.ToTS.Obby:GetChildren()[480],
        workspace.Towers.ToTS.Obby:GetChildren()[534],
        workspace.Towers.ToTS.Obby:GetChildren()[405], --F3
        workspace.Towers.ToTS.Obby:GetChildren()[136],
        workspace.Towers.ToTS.Obby:GetChildren()[386],
        workspace.Towers.ToTS.Obby:GetChildren()[349],
        workspace.Towers.ToTS.Obby:GetChildren()[307],
        workspace.Towers.ToTS.Obby:GetChildren()[159],
        workspace.Towers.ToTS.Obby:GetChildren()[408],
        workspace.Towers.ToTS.Obby:GetChildren()[400],
        workspace.Towers.ToTS.Obby:GetChildren()[399],
        workspace.Towers.ToTS.Obby:GetChildren()[340],
        workspace.Towers.ToTS.Obby:GetChildren()[376],
        workspace.Towers.ToTS.Obby:GetChildren()[331],
        workspace.Towers.ToTS.Obby:GetChildren()[339],
        workspace.Towers.ToTS.Obby:GetChildren()[328],
        workspace.Towers.ToTS.Obby:GetChildren()[375],
        workspace.Towers.ToTS.Obby:GetChildren()[326],
        workspace.Towers.ToTS.Obby:GetChildren()[351],
        workspace.Towers.ToTS.Obby:GetChildren()[31], --F4
        workspace.Towers.ToTS.Obby:GetChildren()[88],
        workspace.Towers.ToTS.Obby:GetChildren()[99],
        workspace.Towers.ToTS.Obby:GetChildren()[64],
        workspace.Towers.ToTS.Obby:GetChildren()[93],
        workspace.Towers.ToTS.Obby:GetChildren()[317],
        workspace.Towers.ToTS.Obby:GetChildren()[59],
        workspace.Towers.ToTS.Obby:GetChildren()[347],
        workspace.Towers.ToTS.Obby:GetChildren()[138],
        workspace.ClientParts.KillBricks:GetChildren()[27],
        workspace.Towers.ToTS.Obby:GetChildren()[169],
        workspace.Towers.ToTS.Obby:GetChildren()[32],
        workspace.Towers.ToTS.Obby:GetChildren()[29],
        workspace.Towers.ToTS.Obby:GetChildren()[126],
        workspace.ClientParts["Disappearing Platforms"]:GetChildren()[13], --F5
        workspace.ClientParts["Disappearing Platforms"]:GetChildren()[11],
        workspace.ClientParts["Disappearing Platforms"]:GetChildren()[10],
        workspace.ClientParts["Disappearing Platforms"]:GetChildren()[15],
        workspace.ClientParts["Disappearing Platforms"]:GetChildren()[4],
        workspace.ClientParts["Disappearing Platforms"]:GetChildren()[6],
        workspace.ClientParts["Disappearing Platforms"]:GetChildren()[17],
        workspace.ClientParts["Disappearing Platforms"]:GetChildren()[7],
        workspace.ClientParts["Disappearing Platforms"]:GetChildren()[24],
        workspace.ClientParts["Disappearing Platforms"]:GetChildren()[27],
        workspace.ClientParts["Disappearing Platforms"]:GetChildren()[31],
        workspace.ClientParts["Disappearing Platforms"]:GetChildren()[29],
        workspace.ClientParts["Disappearing Platforms"]:GetChildren()[39],
        workspace.ClientParts["Disappearing Platforms"]:GetChildren()[33],
        workspace.ClientParts["Disappearing Platforms"]:GetChildren()[41],
        workspace.ClientParts["Disappearing Platforms"]:GetChildren()[35],
        workspace.Towers.ToTS.Obby:GetChildren()[574], --F6
        workspace.Towers.ToTS.Obby:GetChildren()[583],
        workspace.Towers.ToTS.Obby:GetChildren()[576],
        workspace.Towers.ToTS.Obby:GetChildren()[567],
        workspace.Towers.ToTS.Obby:GetChildren()[26],
        workspace.Towers.ToTS.Obby:GetChildren()[20],
        workspace.Towers.ToTS.Obby:GetChildren()[568],
        workspace.Towers.ToTS.Obby:GetChildren()[569],
        workspace.Towers.ToTS.Obby:GetChildren()[562],
        workspace.Towers.ToTS.Obby:GetChildren()[9],
        workspace.Towers.ToTS.Obby:GetChildren()[585],
        workspace.Towers.ToTS.Obby:GetChildren()[565],
        workspace.Towers.ToTS.Obby:GetChildren()[100],
        workspace.Towers.ToTS.Obby:GetChildren()[362],
        workspace.Towers.ToTS.Obby:GetChildren()[578],
        workspace.Towers.ToTS.Obby:GetChildren()[581],
        workspace.Towers.ToTS.Obby:GetChildren()[580],
        workspace.Towers.ToTS.Obby:GetChildren()[573],
        workspace.Towers.ToTS.Obby:GetChildren()[379],
        workspace.Towers.ToTS.Obby:GetChildren()[82],
        workspace.Towers.ToTS.Obby:GetChildren()[10],
        workspace.Towers.ToTS.Obby:GetChildren()[324],
        workspace.Towers.ToTS.Obby:GetChildren()[142],
        workspace.Towers.ToTS.Obby:GetChildren()[117], --F7
        workspace.Towers.ToTS.Obby:GetChildren()[343],
        workspace.Towers.ToTS.Obby:GetChildren()[61],
        workspace.Towers.ToTS.Obby:GetChildren()[14],
        workspace.Towers.ToTS.Obby:GetChildren()[15],
        workspace.Towers.ToTS.Obby:GetChildren()[592],
        workspace.Towers.ToTS.Obby:GetChildren()[97],
        workspace.Towers.ToTS.Obby:GetChildren()[594],
        workspace.Towers.ToTS.Obby:GetChildren()[590],
        workspace.Towers.ToTS.Obby:GetChildren()[63],
        workspace.Towers.ToTS.Obby:GetChildren()[602],
        workspace.Towers.ToTS.Obby:GetChildren()[163],
        workspace.Towers.ToTS.Obby:GetChildren()[230],
        workspace.Towers.ToTS.Obby:GetChildren()[175],
        workspace.Towers.ToTS.Obby:GetChildren()[252],
        workspace.Towers.ToTS.Obby:GetChildren()[249],
        workspace.Towers.ToTS.Obby:GetChildren()[134],
        workspace.Towers.ToTS.Obby:GetChildren()[272],
        workspace.Towers.ToTS.Obby:GetChildren()[108],
        workspace.Towers.ToTS.Obby:GetChildren()[118], --F8
        workspace.Towers.ToTS.Obby:GetChildren()[62],
        workspace.ClientParts.KillBricks:GetChildren()[17],
        workspace.Towers.ToTS.Obby:GetChildren()[68],
        workspace.ClientParts.KillBricks:GetChildren()[25],
        workspace.Towers.ToTS.Obby:GetChildren()[70],
        workspace.ClientParts.KillBricks:GetChildren()[42],
        workspace.Towers.ToTS.Obby:GetChildren()[72],
        workspace.ClientParts.KillBricks:GetChildren()[11],
        workspace.ClientParts.KillBricks:GetChildren()[4],
        workspace.ClientParts.KillBricks:GetChildren()[12],
        workspace.ClientParts.KillBricks:GetChildren()[3],
        workspace.Towers.ToTS.Obby:GetChildren()[75],
        workspace.Towers.ToTS.Obby:GetChildren()[2],
        workspace.ClientParts.KillBricks:GetChildren()[34],
        workspace.Towers.ToTS.Obby:GetChildren()[53],
        workspace.Towers.ToTS.Obby:GetChildren()[601],
        workspace.Towers.ToTS.Obby:GetChildren()[596],
        workspace.Towers.ToTS.Obby:GetChildren()[589], --F9
        workspace.Towers.ToTS.Obby:GetChildren()[104],
        workspace.Towers.ToTS.Obby:GetChildren()[212],
        workspace.Towers.ToTS.Obby:GetChildren()[170],
        workspace.Towers.ToTS.Obby:GetChildren()[260],
        workspace.Towers.ToTS.Obby:GetChildren()[285],
        workspace.Towers.ToTS.Obby:GetChildren()[228],
        workspace.Towers.ToTS.Obby:GetChildren()[255],
        workspace.Towers.ToTS.Obby:GetChildren()[146],
        workspace.Towers.ToTS.Obby:GetChildren()[135],
        workspace.Towers.ToTS.Obby:GetChildren()[114],
        workspace.Towers.ToTS.Obby:GetChildren()[140],
        workspace.Towers.ToTS.Obby:GetChildren()[279],
        workspace.Towers.ToTS.Obby:GetChildren()[221],
        workspace.Towers.ToTS.Obby:GetChildren()[223],
        workspace.Towers.ToTS.Obby:GetChildren()[270],
        workspace.Towers.ToTS.Obby:GetChildren()[216],
        workspace.Towers.ToTS.Obby:GetChildren()[239],
        workspace.Towers.ToTS.Obby:GetChildren()[234],
        workspace.Towers.ToTS.Obby:GetChildren()[243],
        workspace.Towers.ToTS.Obby:GetChildren()[247],
        workspace.Towers.ToTS.Obby:GetChildren()[214],
        workspace.Towers.ToTS.Obby:GetChildren()[110],
        workspace.Towers.ToTS.WinPad
        
        
        
    }
end
