return function()
    return {
        workspace.ClientParts:GetChildren()[32]:GetChildren()[2],
        workspace.Towers.CoU.Obby:GetChildren()[15],
        workspace.Towers.CoU.Obby:GetChildren()[17],
        workspace.Towers.CoU.Obby:GetChildren()[19],
        workspace.Towers.CoU.Obby:GetChildren()[21],
        workspace.Towers.CoU.Obby:GetChildren()[23],
        workspace.Towers.CoU.Obby:GetChildren()[27],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[6],
        workspace.Towers.CoU.Obby:GetChildren()[395],
        workspace.Towers.CoU.Obby:GetChildren()[28],
        workspace.Towers.CoU.Obby:GetChildren()[29],
        workspace.Towers.CoU.Obby:GetChildren()[30],
        workspace.Towers.CoU.Obby:GetChildren()[31],
        workspace.Towers.CoU.Obby:GetChildren()[1543],
        workspace.Towers.CoU.Obby:GetChildren()[89],
        workspace.Towers.CoU.Obby:GetChildren()[33],
        workspace.Towers.CoU.Obby:GetChildren()[32],
        workspace.Towers.CoU.Obby:GetChildren()[40],
        workspace.Towers.CoU.Obby:GetChildren()[39],
        workspace.Towers.CoU.Obby:GetChildren()[41],
        workspace.Towers.CoU.Obby:GetChildren()[43],
        workspace.Towers.CoU.Obby:GetChildren()[45],
        workspace.Towers.CoU.Obby:GetChildren()[42],
        workspace.Towers.CoU.Obby:GetChildren()[47],
        workspace.Towers.CoU.Obby:GetChildren()[48],
        workspace.Towers.CoU.Obby:GetChildren()[52],
        workspace.Towers.CoU.Obby:GetChildren()[53],
        workspace.Towers.CoU.Obby:GetChildren()[56],
        workspace.Towers.CoU.Obby:GetChildren()[61],
        workspace.Towers.CoU.Obby:GetChildren()[55],
        workspace.Towers.CoU.Obby:GetChildren()[60],
        workspace.Towers.CoU.Obby:GetChildren()[59],
        workspace.Towers.CoU.Obby:GetChildren()[62],
        workspace.Towers.CoU.Obby:GetChildren()[63],
        workspace.Towers.CoU.Obby:GetChildren()[64],
        workspace.Towers.CoU.Obby:GetChildren()[65],
        workspace.ClientParts:GetChildren()[65]:GetChildren()[1],
        workspace.ClientParts:GetChildren()[34]:GetChildren()[2],
        workspace.Towers.CoU.Obby:GetChildren()[51],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[8],
        workspace.Towers.CoU.Obby:GetChildren()[68],
        workspace.Towers.CoU.Obby:GetChildren()[70],
        workspace.Towers.CoU.Obby:GetChildren()[69],
        workspace.Towers.CoU.Obby:GetChildren()[71],
        workspace.Towers.CoU.Obby:GetChildren()[72],
        workspace.Towers.CoU.Obby:GetChildren()[76],
        workspace.Towers.CoU.Obby:GetChildren()[74],
        workspace.Towers.CoU.Obby:GetChildren()[80],
        workspace.Towers.CoU.Obby:GetChildren()[78],
        workspace.Towers.CoU.Obby:GetChildren()[77],
        workspace.Towers.CoU.Obby:GetChildren()[212],
        workspace.Towers.CoU.Obby:GetChildren()[81],
        workspace.Towers.CoU.Obby:GetChildren()[82],
        workspace.Towers.CoU.Obby:GetChildren()[83],
        workspace.Towers.CoU.Obby:GetChildren()[85],
        workspace.Towers.CoU.Obby:GetChildren()[232],
        workspace.Towers.CoU.Obby:GetChildren()[97],
        workspace.Towers.CoU.Obby:GetChildren()[98],
        workspace.Towers.CoU.Obby:GetChildren()[99],
        workspace.Towers.CoU.Obby:GetChildren()[205],
        workspace.Towers.CoU.Obby:GetChildren()[206],
        workspace.Towers.CoU.Obby:GetChildren()[101],
        workspace.Towers.CoU.Obby:GetChildren()[103],
        workspace.Towers.CoU.Obby:GetChildren()[104],
        workspace.Towers.CoU.Obby:GetChildren()[107],
        workspace.Towers.CoU.Obby:GetChildren()[105],
        workspace.Towers.CoU.Obby:GetChildren()[109],
        workspace.Towers.CoU.Obby:GetChildren()[110],
        workspace.Towers.CoU.Obby:GetChildren()[255],
        workspace.Towers.CoU.Obby:GetChildren()[113],
        workspace.ClientParts:GetChildren()[35]:GetChildren()[1],
        workspace.ClientParts:GetChildren()[64]:GetChildren()[1],
        workspace.Towers.CoU.Obby:GetChildren()[341],
        workspace.Towers.CoU.Obby:GetChildren()[123],
        workspace.Towers.CoU.Obby:GetChildren()[124],
        workspace.Towers.CoU.Obby:GetChildren()[125],
        workspace.Towers.CoU.Obby:GetChildren()[126],
        workspace.Towers.CoU.Obby:GetChildren()[127],
        workspace.Towers.CoU.Obby:GetChildren()[130],
        workspace.Towers.CoU.Obby:GetChildren()[135],
        workspace.Towers.CoU.Obby:GetChildren()[133],
        workspace.Towers.CoU.Obby:GetChildren()[136],
        workspace.Towers.CoU.Obby:GetChildren()[137],
        workspace.ClientParts:GetChildren()[36]:GetChildren()[3],
        workspace.ClientParts:GetChildren()[37]:GetChildren()[3],
        workspace.Towers.CoU.Obby:GetChildren()[139],
        workspace.Towers.CoU.Obby:GetChildren()[142],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[358],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[355],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[345],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[356],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[342],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[350],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[359],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[347],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[346],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[341],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[357],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[344],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[354],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[351],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[352],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[360],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[349],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[348],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[353],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[343],
        workspace.Towers.CoU.Obby:GetChildren()[164],
        workspace.Towers.CoU.Obby:GetChildren()[172],
        workspace.Towers.CoU.Obby:GetChildren()[642],
        workspace.Towers.CoU.Obby:GetChildren()[173],
        workspace.Towers.CoU.Obby:GetChildren()[143],
        workspace.ClientParts:GetChildren()[38]:GetChildren()[1],
        workspace.Towers.CoU.Obby:GetChildren()[189],
        workspace.ClientParts:GetChildren()[39]:GetChildren()[2],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[10],
        workspace.Towers.CoU.Obby:GetChildren()[190],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[11],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[12],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[13],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[14],
        workspace.Towers.CoU.Obby:GetChildren()[191],
        workspace.Towers.CoU.Obby:GetChildren()[196],
        workspace.Towers.CoU.Obby:GetChildren()[198],
        workspace.Towers.CoU.Obby:GetChildren()[193],
        workspace.Towers.CoU.Obby:GetChildren()[200],
        workspace.Towers.CoU.Obby:GetChildren()[199],
        workspace.Towers.CoU.Obby:GetChildren()[204],
        workspace.Towers.CoU.Obby:GetChildren()[203],
        workspace.Towers.CoU.Obby:GetChildren()[100],
        workspace.Towers.CoU.Obby:GetChildren()[207],
        workspace.Towers.CoU.Obby:GetChildren()[210],
        workspace.Towers.CoU.Obby:GetChildren()[209],
        workspace.Towers.CoU.Obby:GetChildren()[215],
        workspace.Towers.CoU.Obby:GetChildren()[230],
        workspace.Towers.CoU.Obby:GetChildren()[231],
        workspace.Towers.CoU.Obby:GetChildren()[216],
        workspace.Towers.CoU.Obby:GetChildren()[221],
        workspace.Towers.CoU.Obby:GetChildren()[227],
        workspace.Towers.CoU.Obby:GetChildren()[226],
        workspace.Towers.CoU.Obby:GetChildren()[236],
        workspace.Towers.CoU.Obby:GetChildren()[1313],
        workspace.Towers.CoU.Obby:GetChildren()[237],
        workspace.Towers.CoU.Obby:GetChildren()[235],
        workspace.Towers.CoU.Obby:GetChildren()[1912],
        workspace.Towers.CoU.Obby:GetChildren()[240],
        workspace.Towers.CoU.Obby:GetChildren()[242],
        workspace.Towers.CoU.Obby:GetChildren()[243],
        workspace.Towers.CoU.Obby:GetChildren()[244],
        workspace.Towers.CoU.Obby:GetChildren()[246],
        workspace.Towers.CoU.Obby:GetChildren()[1963],
        workspace.Towers.CoU.Obby:GetChildren()[247],
        workspace.Towers.CoU.Obby:GetChildren()[1962],
        workspace.Towers.CoU.Obby:GetChildren()[250],
        workspace.Towers.CoU.Obby:GetChildren()[253],
        workspace.Towers.CoU.Obby:GetChildren()[259],
        workspace.Towers.CoU.Obby:GetChildren()[1946],
        workspace.Towers.CoU.Obby:GetChildren()[252],
        workspace.Towers.CoU.Obby:GetChildren()[249],
        workspace.Towers.CoU.Obby:GetChildren()[248],
        workspace.ClientParts:GetChildren()[40]:GetChildren()[2],
        workspace.Towers.CoU.Obby:GetChildren()[229],
        workspace.Towers.CoU.Obby:GetChildren()[1927],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[16],
        workspace.Towers.CoU.Obby:GetChildren()[262],
        workspace.Towers.CoU.Obby:GetChildren()[509],
        workspace.Towers.CoU.Obby:GetChildren()[265],
        workspace.Towers.CoU.Obby:GetChildren()[267],
        workspace.Towers.CoU.Obby:GetChildren()[268],
        workspace.Towers.CoU.Obby:GetChildren()[269],
        workspace.Towers.CoU.Obby:GetChildren()[270],
        workspace.Towers.CoU.Obby:GetChildren()[271],
        workspace.Towers.CoU.Obby:GetChildren()[272],
        workspace.Towers.CoU.Obby:GetChildren()[273],
        workspace.Towers.CoU.Obby:GetChildren()[274],
        workspace.Towers.CoU.Obby:GetChildren()[278],
        workspace.Towers.CoU.Obby:GetChildren()[282],
        workspace.Towers.CoU.Obby:GetChildren()[283],
        workspace.Towers.CoU.Obby:GetChildren()[266],
        workspace.Towers.CoU.Obby:GetChildren()[276],
        workspace.Towers.CoU.Obby:GetChildren()[289],
        workspace.Towers.CoU.Obby:GetChildren()[286],
        workspace.Towers.CoU.Obby:GetChildren()[285],
        workspace.Towers.CoU.Obby:GetChildren()[284],
        workspace.Towers.CoU.Obby:GetChildren()[281],
        workspace.Towers.CoU.Obby:GetChildren()[280],
        workspace.Towers.CoU.Obby:GetChildren()[288],
        workspace.Towers.CoU.Obby:GetChildren()[275],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[327],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[334],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[333],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[332],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[330],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[331],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[338],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[329],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[326],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[325],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[337],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[321],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[335],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[324],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[336],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[323],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[340],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[339],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[322],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[328],
        workspace.Towers.CoU.Obby:GetChildren()[310],
        workspace.ClientParts:GetChildren()[43]:GetChildren()[3],
        workspace.Towers.CoU.Obby:GetChildren()[312],
        workspace.ClientParts:GetChildren()[44]:GetChildren()[3],
        workspace.Towers.CoU.Obby:GetChildren()[314],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[301],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[302],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[287],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[316],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[269],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[312],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[276],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[314],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[299],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[298],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[264],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[320],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[308],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[286],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[309],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[297],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[295],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[292],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[291],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[313],
        workspace.Towers.CoU.Obby:GetChildren()[317],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[311],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[293],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[282],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[296],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[300],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[294],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[280],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[289],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[285],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[268],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[284],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[288],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[281],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[310],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[307],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[306],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[303],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[305],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[317],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[304],
        workspace.Towers.CoU.Obby:GetChildren()[318],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[315],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[290],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[283],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[279],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[278],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[267],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[277],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[275],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[274],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[273],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[272],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[319],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[318],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[271],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[270],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[266],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[261],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[262],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[263],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[265],
        workspace.Towers.CoU.Obby:GetChildren()[319],
        workspace.Towers.CoU.Obby:GetChildren()[381],
        workspace.Towers.CoU.Obby:GetChildren()[382],
        workspace.Towers.CoU.Obby:GetChildren()[380],
        workspace.Towers.CoU.Obby:GetChildren()[383],
        workspace.Towers.CoU.Obby:GetChildren()[384],
        workspace.Towers.CoU.Obby:GetChildren()[385],
        workspace.Towers.CoU.Obby:GetChildren()[387],
        workspace.Towers.CoU.Obby:GetChildren()[388],
        workspace.Towers.CoU.Obby:GetChildren()[389],
        workspace.Towers.CoU.Obby:GetChildren()[390],
        workspace.Towers.CoU.Obby:GetChildren()[392],
        workspace.Towers.CoU.Obby:GetChildren()[391],
        workspace.Towers.CoU.Obby:GetChildren()[393],
        workspace.Towers.CoU.Obby:GetChildren()[394],
        workspace.Towers.CoU.Obby:GetChildren()[399],
        workspace.Towers.CoU.Obby:GetChildren()[400],
        workspace.Towers.CoU.Obby:GetChildren()[401],
        workspace.Towers.CoU.Obby:GetChildren()[402],
        workspace.Towers.CoU.Obby:GetChildren()[403],
        workspace.Towers.CoU.Obby:GetChildren()[404],
        workspace.Towers.CoU.Obby:GetChildren()[405],
        workspace.Towers.CoU.Obby:GetChildren()[406],
        workspace.Towers.CoU.Obby:GetChildren()[1957],
        workspace.Towers.CoU.Obby:GetChildren()[410],
        workspace.Towers.CoU.Obby:GetChildren()[411],
        workspace.Towers.CoU.Obby:GetChildren()[412],
        workspace.Towers.CoU.Obby:GetChildren()[407],
        workspace.Towers.CoU.Obby:GetChildren()[413],
        workspace.Towers.CoU.Obby:GetChildren()[1956],
        workspace.Towers.CoU.Obby:GetChildren()[416],
        workspace.Towers.CoU.Obby:GetChildren()[417],
        workspace.Towers.CoU.Obby:GetChildren()[418],
        workspace.Towers.CoU.Obby:GetChildren()[419],
        workspace.Towers.CoU.Obby:GetChildren()[420],
        workspace.Towers.CoU.Obby:GetChildren()[421],
        workspace.Towers.CoU.Obby:GetChildren()[422],
        workspace.Towers.CoU.Obby:GetChildren()[423],
        workspace.Towers.CoU.Obby:GetChildren()[424],
        workspace.Towers.CoU.Obby:GetChildren()[425],
        workspace.Towers.CoU.Obby:GetChildren()[426],
        workspace.Towers.CoU.Obby:GetChildren()[427],
        workspace.Towers.CoU.Obby:GetChildren()[428],
        workspace.Towers.CoU.Obby:GetChildren()[431],
        workspace.Towers.CoU.Obby:GetChildren()[430],
        workspace.Towers.CoU.Obby:GetChildren()[429],
        workspace.Towers.CoU.Obby:GetChildren()[414],
        workspace.Towers.CoU.Obby:GetChildren()[439],
        workspace.Towers.CoU.Obby:GetChildren()[433],
        workspace.Towers.CoU.Obby:GetChildren()[440],
        workspace.Towers.CoU.Obby:GetChildren()[441],
        workspace.ClientParts:GetChildren()[45]:GetChildren()[1],
        workspace.ClientParts:GetChildren()[46]:GetChildren()[1],
        workspace.ClientParts:GetChildren()[46]:GetChildren()[2],
        workspace.Towers.CoU.Obby:GetChildren()[443],
        workspace.Towers.CoU.Obby:GetChildren()[445],
        workspace.Towers.CoU.Obby:GetChildren()[1966],
        workspace.Towers.CoU.Obby:GetChildren()[451],
        workspace.Towers.CoU.Obby:GetChildren()[1967],
        workspace.Towers.CoU.Obby:GetChildren()[1969],
        workspace.Towers.CoU.Obby:GetChildren()[1968],
        workspace.Towers.CoU.Obby:GetChildren()[452],
        workspace.Towers.CoU.Obby:GetChildren()[1975],
        workspace.Towers.CoU.Obby:GetChildren()[146],
        workspace.Towers.CoU.Obby:GetChildren()[1458],
        workspace.Towers.CoU.Obby:GetChildren()[148],
        workspace.Towers.CoU.Obby:GetChildren()[1970],
        workspace.Towers.CoU.Obby:GetChildren()[560],
        workspace.Towers.CoU.Obby:GetChildren()[1972],
        workspace.Towers.CoU.Obby:GetChildren()[453],
        workspace.ClientParts.KillBricks:GetChildren()[12],
        workspace.Towers.CoU.Obby:GetChildren()[450],
        workspace.Towers.CoU.Obby:GetChildren()[457],
        workspace.Towers.CoU.Obby:GetChildren()[458],
        workspace.Towers.CoU.Obby:GetChildren()[456],
        workspace.Towers.CoU.Obby:GetChildren()[454],
        workspace.Towers.CoU.Obby:GetChildren()[464],
        workspace.Towers.CoU.Obby:GetChildren()[1928],
        workspace.Towers.CoU.Obby:GetChildren()[466],
        workspace.Towers.CoU.Obby:GetChildren()[472],
        workspace.Towers.CoU.Obby:GetChildren()[471],
        workspace.Towers.CoU.Obby:GetChildren()[468],
        workspace.Towers.CoU.Obby:GetChildren()[476],
        workspace.Towers.CoU.Obby:GetChildren()[477],
        workspace.Towers.CoU.Obby:GetChildren()[475],
        workspace.Towers.CoU.Obby:GetChildren()[478],
        workspace.Towers.CoU.Obby:GetChildren()[479],
        workspace.Towers.CoU.Obby:GetChildren()[480],
        workspace.ClientParts:GetChildren()[48]:GetChildren()[1],
        workspace.Towers.CoU.Obby:GetChildren()[484],
        workspace.Towers.CoU.Obby:GetChildren()[485],
        workspace.ClientParts:GetChildren()[60]:GetChildren()[1],
        workspace.Towers.CoU.Obby:GetChildren()[559],
        workspace.Towers.CoU.Obby:GetChildren()[489],
        workspace.Towers.CoU.Obby:GetChildren()[495],
        workspace.Towers.CoU.Obby:GetChildren()[1929],
        workspace.ClientParts:GetChildren()[47]:GetChildren()[2],
        workspace.Towers.CoU.Obby:GetChildren()[493],
        workspace.Towers.CoU.Obby:GetChildren()[494],
        workspace.Towers.CoU.Obby:GetChildren()[496],
        workspace.Towers.CoU.Obby:GetChildren()[497],
        workspace.Towers.CoU.Obby:GetChildren()[508],
        workspace.Towers.CoU.Obby:GetChildren()[500],
        workspace.Towers.CoU.Obby:GetChildren()[483],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[19],
        workspace.Towers.CoU.Obby:GetChildren()[481],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[17],
        workspace.Towers.CoU.Obby:GetChildren()[502],
        workspace.Towers.CoU.Obby:GetChildren()[503],
        workspace.Towers.CoU.Obby:GetChildren()[504],
        workspace.Towers.CoU.Obby:GetChildren()[498],
        workspace.Towers.CoU.Obby:GetChildren()[505],
        workspace.Towers.CoU.Obby:GetChildren()[507],
        workspace.Towers.CoU.Obby:GetChildren()[149],
        workspace.Towers.CoU.Obby:GetChildren()[557],
        workspace.Towers.CoU.Obby:GetChildren()[154],
        workspace.Towers.CoU.Obby:GetChildren()[499],
        workspace.Towers.CoU.Obby:GetChildren()[555],
        workspace.Towers.CoU.Obby:GetChildren()[556],
        workspace.ClientParts:GetChildren()[66]:GetChildren()[2],
        workspace.Towers.CoU.Obby:GetChildren()[303],
        workspace.Towers.CoU.Obby:GetChildren()[562],
        workspace.Towers.CoU.Obby:GetChildren()[570],
        workspace.Towers.CoU.Obby:GetChildren()[571],
        workspace.Towers.CoU.Obby:GetChildren()[572],
        workspace.Towers.CoU.Obby:GetChildren()[915],
        workspace.ClientParts:GetChildren()[50]:GetChildren()[1],
        workspace.Towers.CoU.Obby:GetChildren()[573],
        workspace.Towers.CoU.Obby:GetChildren()[574],
        workspace.Towers.CoU.Obby:GetChildren()[576],
        workspace.Towers.CoU.Obby:GetChildren()[577],
        workspace.Towers.CoU.Obby:GetChildren()[578],
        workspace.Towers.CoU.Obby:GetChildren()[575],
        workspace.Towers.CoU.Obby:GetChildren()[584],
        workspace.Towers.CoU.Obby:GetChildren()[589],
        workspace.ClientParts:GetChildren()[51]:GetChildren()[3],
        workspace.Towers.CoU.Obby:GetChildren()[590],
        workspace.Towers.CoU.Obby:GetChildren()[594],
        workspace.Towers.CoU.Obby:GetChildren()[591],
        workspace.ClientParts:GetChildren()[52]:GetChildren()[3],
        workspace.Towers.CoU.Obby:GetChildren()[581],
        workspace.Towers.CoU.Obby:GetChildren()[595],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[246],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[245],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[260],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[256],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[253],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[244],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[252],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[249],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[241],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[248],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[254],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[257],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[251],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[250],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[247],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[259],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[243],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[255],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[258],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[242],
        workspace.Towers.CoU.Obby:GetChildren()[598],
        workspace.Towers.CoU.Obby:GetChildren()[546],
        workspace.Towers.CoU.Obby:GetChildren()[548],
        workspace.Towers.CoU.Obby:GetChildren()[620],
        workspace.Towers.CoU.Obby:GetChildren()[622],
        workspace.Towers.CoU.Obby:GetChildren()[623],
        workspace.Towers.CoU.Obby:GetChildren()[905],
        workspace.Towers.CoU.Obby:GetChildren()[630],
        workspace.Towers.CoU.Obby:GetChildren()[625],
        workspace.Towers.CoU.Obby:GetChildren()[624],
        workspace.Towers.CoU.Obby:GetChildren()[627],
        workspace.Towers.CoU.Obby:GetChildren()[522],
        workspace.Towers.CoU.Obby:GetChildren()[521],
        workspace.Towers.CoU.Obby:GetChildren()[629],
        workspace.ClientParts:GetChildren()[53]:GetChildren()[3],
        workspace.Towers.CoU.Obby:GetChildren()[1493],
        workspace.Towers.CoU.Obby:GetChildren()[1495],
        workspace.Towers.CoU.Obby:GetChildren()[1494],
        workspace.Towers.CoU.Obby:GetChildren()[528],
        workspace.Towers.CoU.Obby:GetChildren()[529],
        workspace.Towers.CoU.Obby:GetChildren()[533],
        workspace.Towers.CoU.Obby:GetChildren()[535],
        workspace.Towers.CoU.Obby:GetChildren()[538],
        workspace.Towers.CoU.Obby:GetChildren()[291],
        workspace.Towers.CoU.Obby:GetChildren()[540],
        workspace.Towers.CoU.Obby:GetChildren()[517],
        workspace.Towers.CoU.Obby:GetChildren()[628],
        workspace.Towers.CoU.Obby:GetChildren()[644],
        workspace.Towers.CoU.Obby:GetChildren()[645],
        workspace.Towers.CoU.Obby:GetChildren()[911],
        workspace.Towers.CoU.Obby:GetChildren()[647],
        workspace.Towers.CoU.Obby:GetChildren()[649],
        workspace.Towers.CoU.Obby:GetChildren()[653],
        workspace.Towers.CoU.Obby:GetChildren()[652],
        workspace.Towers.CoU.Obby:GetChildren()[648],
        workspace.Towers.CoU.Obby:GetChildren()[646],
        workspace.Towers.CoU.Obby:GetChildren()[654],
        workspace.Towers.CoU.Obby:GetChildren()[655],
        workspace.Towers.CoU.Obby:GetChildren()[657],
        workspace.Towers.CoU.Obby:GetChildren()[656],
        workspace.Towers.CoU.Obby:GetChildren()[659],
        workspace.Towers.CoU.Obby:GetChildren()[663],
        workspace.Towers.CoU.Obby:GetChildren()[662],
        workspace.Towers.CoU.Obby:GetChildren()[660],
        workspace.ClientParts:GetChildren()[54]:GetChildren()[1],
        workspace.Towers.CoU.Obby:GetChildren()[665],
        workspace.Towers.CoU.Obby:GetChildren()[666],
        workspace.Towers.CoU.Obby:GetChildren()[672],
        workspace.Towers.CoU.Obby:GetChildren()[667],
        workspace.Towers.CoU.Obby:GetChildren()[908],
        workspace.Towers.CoU.Obby:GetChildren()[674],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[240],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[230],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[236],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[224],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[237],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[239],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[221],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[238],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[235],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[228],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[234],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[233],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[232],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[227],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[229],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[226],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[222],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[225],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[223],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[231],
        workspace.Towers.CoU.Obby:GetChildren()[698],
        workspace.Towers.CoU.Obby:GetChildren()[910],
        workspace.Towers.CoU.Obby:GetChildren()[700],
        workspace.Towers.CoU.Obby:GetChildren()[909],
        workspace.Towers.CoU.Obby:GetChildren()[697],
        workspace.Towers.CoU.Obby:GetChildren()[675],
        workspace.Towers.CoU.Obby:GetChildren()[701],
        workspace.Towers.CoU.Obby:GetChildren()[702],
        workspace.Towers.CoU.Obby:GetChildren()[703],
        workspace.Towers.CoU.Obby:GetChildren()[704],
        workspace.Towers.CoU.Obby:GetChildren()[707],
        workspace.Towers.CoU.Obby:GetChildren()[709],
        workspace.Towers.CoU.Obby:GetChildren()[708],
        workspace.Towers.CoU.Obby:GetChildren()[673],
        workspace.Towers.CoU.Obby:GetChildren()[710],
        workspace.Towers.CoU.Obby:GetChildren()[712],
        workspace.Towers.CoU.Obby:GetChildren()[713],
        workspace.Towers.CoU.Obby:GetChildren()[714],
        workspace.Towers.CoU.Obby:GetChildren()[1931],
        workspace.Towers.CoU.Obby:GetChildren()[716],
        workspace.Towers.CoU.Obby:GetChildren()[719],
        workspace.Towers.CoU.Obby:GetChildren()[721],
        workspace.Towers.CoU.Obby:GetChildren()[720],
        workspace.Towers.CoU.Obby:GetChildren()[670],
        workspace.Towers.CoU.Obby:GetChildren()[728],
        workspace.Towers.CoU.Obby:GetChildren()[731],
        workspace.Towers.CoU.Obby:GetChildren()[732],
        workspace.Towers.CoU.Obby:GetChildren()[735],
        workspace.Towers.CoU.Obby:GetChildren()[1932],
        workspace.Towers.CoU.Obby:GetChildren()[736],
        workspace.Towers.CoU.Obby:GetChildren()[738],
        workspace.Towers.CoU.Obby:GetChildren()[740],
        workspace.Towers.CoU.Obby:GetChildren()[741],
        workspace.Towers.CoU.Obby:GetChildren()[742],
        workspace.Towers.CoU.Obby:GetChildren()[745],
        workspace.Towers.CoU.Obby:GetChildren()[747],
        workspace.Towers.CoU.Obby:GetChildren()[748],
        workspace.Towers.CoU.Obby:GetChildren()[751],
        workspace.Towers.CoU.Obby:GetChildren()[752],
        workspace.Towers.CoU.Obby:GetChildren()[750],
        workspace.Towers.CoU.Obby:GetChildren()[749],
        workspace.Towers.CoU.Obby:GetChildren()[746],
        workspace.Towers.CoU.Obby:GetChildren()[744],
        workspace.Towers.CoU.Obby:GetChildren()[743],
        workspace.Towers.CoU.Obby:GetChildren()[753],
        workspace.Towers.CoU.Obby:GetChildren()[754],
        workspace.Towers.CoU.Obby:GetChildren()[756],
        workspace.Towers.CoU.Obby:GetChildren()[759],
        workspace.Towers.CoU.Obby:GetChildren()[755],
        workspace.Towers.CoU.Obby:GetChildren()[767],
        workspace.Towers.CoU.Obby:GetChildren()[765],
        workspace.Towers.CoU.Obby:GetChildren()[768],
        workspace.Towers.CoU.Obby:GetChildren()[912],
        workspace.Towers.CoU.Obby:GetChildren()[771],
        workspace.Towers.CoU.Obby:GetChildren()[772],
        workspace.Towers.CoU.Obby:GetChildren()[785],
        workspace.Towers.CoU.Obby:GetChildren()[776],
        workspace.Towers.CoU.Obby:GetChildren()[773],
        workspace.Towers.CoU.Obby:GetChildren()[775],
        workspace.Towers.CoU.Obby:GetChildren()[774],
        workspace.Towers.CoU.Obby:GetChildren()[777],
        workspace.Towers.CoU.Obby:GetChildren()[778],
        workspace.Towers.CoU.Obby:GetChildren()[779],
        workspace.Towers.CoU.Obby:GetChildren()[780],
        workspace.Towers.CoU.Obby:GetChildren()[781],
        workspace.Towers.CoU.Obby:GetChildren()[783],
        workspace.Towers.CoU.Obby:GetChildren()[762],
        workspace.Towers.CoU.Obby:GetChildren()[788],
        workspace.Towers.CoU.Obby:GetChildren()[789],
        workspace.Towers.CoU.Obby:GetChildren()[790],
        workspace.Towers.CoU.Obby:GetChildren()[763],
        workspace.Towers.CoU.Obby:GetChildren()[760],
        workspace.Towers.CoU.Obby:GetChildren()[764],
        workspace.Towers.CoU.Obby:GetChildren()[794],
        workspace.Towers.CoU.Obby:GetChildren()[793],
        workspace.Towers.CoU.Obby:GetChildren()[795],
        workspace.Towers.CoU.Obby:GetChildren()[796],
        workspace.Towers.CoU.Obby:GetChildren()[800],
        workspace.Towers.CoU.Obby:GetChildren()[792],
        workspace.Towers.CoU.Obby:GetChildren()[807],
        workspace.Towers.CoU.Obby:GetChildren()[813],
        workspace.Towers.CoU.Obby:GetChildren()[814],
        workspace.Towers.CoU.Obby:GetChildren()[815],
        workspace.Towers.CoU.Obby:GetChildren()[817],
        workspace.Towers.CoU.Obby:GetChildren()[819],
        workspace.Towers.CoU.Obby:GetChildren()[820],
        workspace.Towers.CoU.Obby:GetChildren()[821],
        workspace.Towers.CoU.Obby:GetChildren()[822],
        workspace.Towers.CoU.Obby:GetChildren()[823],
        workspace.Towers.CoU.Obby:GetChildren()[827],
        workspace.Towers.CoU.Obby:GetChildren()[828],
        workspace.Towers.CoU.Obby:GetChildren()[829],
        workspace.Towers.CoU.Obby:GetChildren()[826],
        workspace.Towers.CoU.Obby:GetChildren()[824],
        workspace.Towers.CoU.Obby:GetChildren()[825],
        workspace.Towers.CoU.Obby:GetChildren()[833],
        workspace.Towers.CoU.Obby:GetChildren()[835],
        workspace.Towers.CoU.Obby:GetChildren()[834],
        workspace.Towers.CoU.Obby:GetChildren()[836],
        workspace.Towers.CoU.Obby:GetChildren()[837],
        workspace.Towers.CoU.Obby:GetChildren()[841],
        workspace.Towers.CoU.Obby:GetChildren()[840],
        workspace.Towers.CoU.Obby:GetChildren()[848],
        workspace.Towers.CoU.Obby:GetChildren()[842],
        workspace.Towers.CoU.Obby:GetChildren()[839],
        workspace.Towers.CoU.Obby:GetChildren()[838],
        workspace.Towers.CoU.Obby:GetChildren()[852],
        workspace.Towers.CoU.Obby:GetChildren()[831],
        workspace.Towers.CoU.Obby:GetChildren()[863],
        workspace.Towers.CoU.Obby:GetChildren()[857],
        workspace.Towers.CoU.Obby:GetChildren()[856],
        workspace.Towers.CoU.Obby:GetChildren()[864],
        workspace.Towers.CoU.Obby:GetChildren()[854],
        workspace.Towers.CoU.Obby:GetChildren()[867],
        workspace.Towers.CoU.Obby:GetChildren()[832],
        workspace.Towers.CoU.Obby:GetChildren()[853],
        workspace.Towers.CoU.Obby:GetChildren()[982],
        workspace.Towers.CoU.Obby:GetChildren()[868],
        workspace.Towers.CoU.Obby:GetChildren()[873],
        workspace.Towers.CoU.Obby:GetChildren()[874],
        workspace.Towers.CoU.Obby:GetChildren()[878],
        workspace.Towers.CoU.Obby:GetChildren()[877],
        workspace.Towers.CoU.Obby:GetChildren()[880],
        workspace.Towers.CoU.Obby:GetChildren()[879],
        workspace.Towers.CoU.Obby:GetChildren()[875],
        workspace.Towers.CoU.Obby:GetChildren()[876],
        workspace.Towers.CoU.Obby:GetChildren()[881],
        workspace.Towers.CoU.Obby:GetChildren()[888],
        workspace.Towers.CoU.Obby:GetChildren()[866],
        workspace.Towers.CoU.Obby:GetChildren()[984],
        workspace.Towers.CoU.Obby:GetChildren()[869],
        workspace.Towers.CoU.Obby:GetChildren()[870],
        workspace.Towers.CoU.Obby:GetChildren()[871],
        workspace.ClientParts:GetChildren()[15]:GetChildren()[2],
        workspace.Towers.CoU.Obby:GetChildren()[889],
        workspace.Towers.CoU.Obby:GetChildren()[892],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[189],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[209],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[186],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[205],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[214],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[206],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[187],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[182],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[188],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[183],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[184],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[185],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[217],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[216],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[220],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[211],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[201],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[210],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[200],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[213],
        workspace.Towers.CoU.Obby:GetChildren()[893],
        workspace.Towers.CoU.Obby:GetChildren()[1622],
        workspace.Towers.CoU.Obby:GetChildren()[914],
        workspace.Towers.CoU.Obby:GetChildren()[1938],
        workspace.Towers.CoU.Obby:GetChildren()[890],
        workspace.Towers.CoU.Obby:GetChildren()[922],
        workspace.Towers.CoU.Obby:GetChildren()[921],
        workspace.Towers.CoU.Obby:GetChildren()[891],
        workspace.Towers.CoU.Obby:GetChildren()[923],
        workspace.Towers.CoU.Obby:GetChildren()[924],
        workspace.Towers.CoU.Obby:GetChildren()[926],
        workspace.Towers.CoU.Obby:GetChildren()[927],
        workspace.Towers.CoU.Obby:GetChildren()[1450],
        workspace.Towers.CoU.Obby:GetChildren()[930],
        workspace.Towers.CoU.Obby:GetChildren()[931],
        workspace.Towers.CoU.Obby:GetChildren()[932],
        workspace.Towers.CoU.Obby:GetChildren()[934],
        workspace.ClientParts:GetChildren()[23]:GetChildren()[2],
        workspace.Towers.CoU.Obby:GetChildren()[928],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[20],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[27],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[28],
        workspace.Towers.CoU.Obby:GetChildren()[929],
        workspace.Towers.CoU.Obby:GetChildren()[935],
        workspace.Towers.CoU.Obby:GetChildren()[936],
        workspace.Towers.CoU.Obby:GetChildren()[937],
        workspace.Towers.CoU.Obby:GetChildren()[938],
        workspace.Towers.CoU.Obby:GetChildren()[1452],
        workspace.Towers.CoU.Obby:GetChildren()[953],
        workspace.Towers.CoU.Obby:GetChildren()[954],
        workspace.Towers.CoU.Obby:GetChildren()[977],
        workspace.Towers.CoU.Obby:GetChildren()[981],
        workspace.Towers.CoU.Obby:GetChildren()[980],
        workspace.Towers.CoU.Obby:GetChildren()[985],
        workspace.Towers.CoU.Obby:GetChildren()[1009],
        workspace.Towers.CoU.Obby:GetChildren()[1017],
        workspace.Towers.CoU.Obby:GetChildren()[987],
        workspace.Towers.CoU.Obby:GetChildren()[988],
        workspace.Towers.CoU.Obby:GetChildren()[989],
        workspace.Towers.CoU.Obby:GetChildren()[991],
        workspace.Towers.CoU.Obby:GetChildren()[994],
        workspace.Towers.CoU.Obby:GetChildren()[995],
        workspace.Towers.CoU.Obby:GetChildren()[979],
        workspace.Towers.CoU.Obby:GetChildren()[997],
        workspace.Towers.CoU.Obby:GetChildren()[996],
        workspace.Towers.CoU.Obby:GetChildren()[1008],
        workspace.Towers.CoU.Obby:GetChildren()[1006],
        workspace.Towers.CoU.Obby:GetChildren()[1005],
        workspace.Towers.CoU.Obby:GetChildren()[300],
        workspace.Towers.CoU.Obby:GetChildren()[1051],
        workspace.Towers.CoU.Obby:GetChildren()[304],
        workspace.Towers.CoU.Obby:GetChildren()[1010],
        workspace.Towers.CoU.Obby:GetChildren()[1012],
        workspace.Towers.CoU.Obby:GetChildren()[1013],
        workspace.Towers.CoU.Obby:GetChildren()[1015],
        workspace.Towers.CoU.Obby:GetChildren()[1016],
        workspace.Towers.CoU.Obby:GetChildren()[309],
        workspace.Towers.CoU.Obby:GetChildren()[1046],
        workspace.Towers.CoU.Obby:GetChildren()[1045],
        workspace.Towers.CoU.Obby:GetChildren()[986],
        workspace.Towers.CoU.Obby:GetChildren()[1019],
        workspace.Towers.CoU.Obby:GetChildren()[1020],
        workspace.Towers.CoU.Obby:GetChildren()[1021],
        workspace.Towers.CoU.Obby:GetChildren()[1024],
        workspace.Towers.CoU.Obby:GetChildren()[1022],
        workspace.Towers.CoU.Obby:GetChildren()[302],
        workspace.Towers.CoU.Obby:GetChildren()[1025],
        workspace.Towers.CoU.Obby:GetChildren()[1026],
        workspace.Towers.CoU.Obby:GetChildren()[1027],
        workspace.Towers.CoU.Obby:GetChildren()[1028],
        workspace.ClientParts:GetChildren()[27]:GetChildren()[2],
        workspace.Towers.CoU.Obby:GetChildren()[1031],
        workspace.Towers.CoU.Obby:GetChildren()[1034],
        workspace.Towers.CoU.Obby:GetChildren()[1036],
        workspace.Towers.CoU.Obby:GetChildren()[1037],
        workspace.Towers.CoU.Obby:GetChildren()[1035],
        workspace.Towers.CoU.Obby:GetChildren()[1038],
        workspace.Towers.CoU.Obby:GetChildren()[1044],
        workspace.Towers.CoU.Obby:GetChildren()[990],
        workspace.Towers.CoU.Obby:GetChildren()[1003],
        workspace.Towers.CoU.Obby:GetChildren()[1042],
        workspace.Towers.CoU.Obby:GetChildren()[353],
        workspace.Towers.CoU.Obby:GetChildren()[1041],
        workspace.Towers.CoU.Frame:GetChildren()[127],
        workspace.Towers.CoU.Obby:GetChildren()[1052],
        workspace.Towers.CoU.Obby:GetChildren()[1056],
        workspace.Towers.CoU.Obby:GetChildren()[1057],
        workspace.Towers.CoU.Obby:GetChildren()[1059],
        workspace.Towers.CoU.Obby:GetChildren()[1058],
        workspace.Towers.CoU.Obby:GetChildren()[1060],
        workspace.Towers.CoU.Obby:GetChildren()[1054],
        workspace.Towers.CoU.Obby:GetChildren()[1055],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[146],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[160],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[144],
        workspace.Towers.CoU.Obby:GetChildren()[1061],
        workspace.Towers.CoU.Obby:GetChildren()[1083],
        workspace.Towers.CoU.Obby:GetChildren()[1091],
        workspace.Towers.CoU.Obby:GetChildren()[1089],
        workspace.Towers.CoU.Obby:GetChildren()[1090],
        workspace.Towers.CoU.Obby:GetChildren()[1084],
        workspace.Towers.CoU.Obby:GetChildren()[1094],
        workspace.Towers.CoU.Obby:GetChildren()[1092],
        workspace.Towers.CoU.Obby:GetChildren()[1093],
        workspace.Towers.CoU.Obby:GetChildren()[1098],
        workspace.Towers.CoU.Obby:GetChildren()[1100],
        workspace.Towers.CoU.Obby:GetChildren()[1102],
        workspace.Towers.CoU.Obby:GetChildren()[1455],
        workspace.Towers.CoU.Obby:GetChildren()[1453],
        workspace.Towers.CoU.Obby:GetChildren()[1118],
        workspace.ClientParts:GetChildren()[21]:GetChildren()[1],
        workspace.Towers.CoU.Obby:GetChildren()[1104],
        workspace.Towers.CoU.Obby:GetChildren()[1948],
        workspace.Towers.CoU.Obby:GetChildren()[1947],
        workspace.ClientParts:GetChildren()[55]:GetChildren()[1],
        workspace.Towers.CoU.Obby:GetChildren()[1109],
        workspace.Towers.CoU.Obby:GetChildren()[1108],
        workspace.Towers.CoU.Obby:GetChildren()[1107],
        workspace.Towers.CoU.Obby:GetChildren()[1105],
        workspace.Towers.CoU.Obby:GetChildren()[1112],
        workspace.Towers.CoU.Obby:GetChildren()[1113],
        workspace.Towers.CoU.Obby:GetChildren()[1953],
        workspace.Towers.CoU.Obby:GetChildren()[1116],
        workspace.Towers.CoU.Obby:GetChildren()[1114],
        workspace.ClientParts:GetChildren()[56]:GetChildren()[1],
        workspace.ClientParts:GetChildren()[20]:GetChildren()[1],
        workspace.Towers.CoU.Obby:GetChildren()[1954],
        workspace.ClientParts:GetChildren()[57]:GetChildren()[1],
        workspace.Towers.CoU.Obby:GetChildren()[1952],
        workspace.Towers.CoU.Obby:GetChildren()[1951],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[24],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[25],
        workspace.Towers.CoU.Obby:GetChildren()[1117],
        workspace.ClientParts:GetChildren()[30]:GetChildren()[3],
        workspace.Towers.CoU.Obby:GetChildren()[1119],
        workspace.Towers.CoU.Obby:GetChildren()[1120],
        workspace.Towers.CoU.Obby:GetChildren()[1126],
        workspace.Towers.CoU.Obby:GetChildren()[1456],
        workspace.Towers.CoU.Obby:GetChildren()[1457],
        workspace.Towers.CoU.Obby:GetChildren()[1127],
        workspace.Towers.CoU.Obby:GetChildren()[1130],
        workspace.Towers.CoU.Obby:GetChildren()[1133],
        workspace.Towers.CoU.Obby:GetChildren()[1131],
        workspace.ClientParts:GetChildren()[22]:GetChildren()[1],
        workspace.Towers.CoU.Obby:GetChildren()[1461],
        workspace.Towers.CoU.Obby:GetChildren()[1906],
        workspace.Towers.CoU.Obby:GetChildren()[1139],
        workspace.Towers.CoU.Obby:GetChildren()[1138],
        workspace.Towers.CoU.Obby:GetChildren()[1135],
        workspace.Towers.CoU.Obby:GetChildren()[1137],
        workspace.Towers.CoU.Obby:GetChildren()[1142],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[22],
        workspace.Towers.CoU.Obby:GetChildren()[1143],
        workspace.Towers.CoU.Obby:GetChildren()[1146],
        workspace.Towers.CoU.Obby:GetChildren()[1148],
        workspace.Towers.CoU.Obby:GetChildren()[1149],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[141],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[140],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[139],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[138],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[133],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[137],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[136],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[135],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[132],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[131],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[130],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[129],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[124],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[126],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[125],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[128],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[127],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[123],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[122],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[134],
        workspace.Towers.CoU.Obby:GetChildren()[1152],
        workspace.Towers.CoU.Obby:GetChildren()[1173],
        workspace.Towers.CoU.Obby:GetChildren()[1174],
        workspace.Towers.CoU.Obby:GetChildren()[1197],
        workspace.Towers.CoU.Obby:GetChildren()[1933],
        workspace.Towers.CoU.Obby:GetChildren()[1934],
        workspace.Towers.CoU.Obby:GetChildren()[1198],
        workspace.Towers.CoU.Obby:GetChildren()[1182],
        workspace.Towers.CoU.Obby:GetChildren()[1192],
        workspace.Towers.CoU.Obby:GetChildren()[1201],
        workspace.Towers.CoU.Obby:GetChildren()[1202],
        workspace.Towers.CoU.Obby:GetChildren()[1204],
        workspace.Towers.CoU.Obby:GetChildren()[1208],
        workspace.Towers.CoU.Obby:GetChildren()[1207],
        workspace.Towers.CoU.Obby:GetChildren()[1205],
        workspace.Towers.CoU.Obby:GetChildren()[1206],
        workspace.Towers.CoU.Obby:GetChildren()[1209],
        workspace.Towers.CoU.Obby:GetChildren()[1210],
        workspace.Towers.CoU.Obby:GetChildren()[1212],
        workspace.Towers.CoU.Obby:GetChildren()[1213],
        workspace.Towers.CoU.Obby:GetChildren()[1211],
        workspace.Towers.CoU.Obby:GetChildren()[1217],
        workspace.Towers.CoU.Obby:GetChildren()[1216],
        workspace.Towers.CoU.Obby:GetChildren()[1214],
        workspace.Towers.CoU.Obby:GetChildren()[1218],
        workspace.Towers.CoU.Obby:GetChildren()[1222],
        workspace.Towers.CoU.Obby:GetChildren()[1935],
        workspace.Towers.CoU.Obby:GetChildren()[1219],
        workspace.Towers.CoU.Obby:GetChildren()[1225],
        workspace.Towers.CoU.Obby:GetChildren()[1230],
        workspace.Towers.CoU.Obby:GetChildren()[1227],
        workspace.Towers.CoU.Obby:GetChildren()[1228],
        workspace.ClientParts.KillBricks:GetChildren()[43],
        workspace.ClientParts.KillBricks:GetChildren()[41],
        workspace.ClientParts.KillBricks:GetChildren()[42],
        workspace.ClientParts.KillBricks:GetChildren()[44],
        workspace.Towers.CoU.Obby:GetChildren()[1235],
        workspace.ClientParts:GetChildren()[19]:GetChildren()[3],
        workspace.Towers.CoU.Obby:GetChildren()[1237],
        workspace.Towers.CoU.Obby:GetChildren()[1241],
        workspace.Towers.CoU.Obby:GetChildren()[297],
        workspace.Towers.CoU.Obby:GetChildren()[1239],
        workspace.Towers.CoU.Obby:GetChildren()[1238],
        workspace.Towers.CoU.Obby:GetChildren()[1243],
        workspace.Towers.CoU.Obby:GetChildren()[1244],
        workspace.Towers.CoU.Obby:GetChildren()[1955],
        workspace.ClientParts:GetChildren()[10]:GetChildren()[1],
        workspace.Towers.CoU.Obby:GetChildren()[1247],
        workspace.Towers.CoU.Obby:GetChildren()[1246],
        workspace.Towers.CoU.Obby:GetChildren()[1245],
        workspace.Towers.CoU.Obby:GetChildren()[1252],
        workspace.Towers.CoU.Obby:GetChildren()[1251],
        workspace.Towers.CoU.Obby:GetChildren()[1250],
        workspace.Towers.CoU.Obby:GetChildren()[1255],
        workspace.Towers.CoU.Obby:GetChildren()[1254],
        workspace.Towers.CoU.Obby:GetChildren()[1253],
        workspace.Towers.CoU.Obby:GetChildren()[1257],
        workspace.Towers.CoU.Obby:GetChildren()[1256],
        workspace.Towers.CoU.Obby:GetChildren()[1259],
        workspace.Towers.CoU.Obby:GetChildren()[1261],
        workspace.Towers.CoU.Obby:GetChildren()[1262],
        workspace.Towers.CoU.Obby:GetChildren()[1258],
        workspace.Towers.CoU.Obby:GetChildren()[1265],
        workspace.Towers.CoU.Obby:GetChildren()[1266],
        workspace.Towers.CoU.Obby:GetChildren()[1263],
        workspace.Towers.CoU.Obby:GetChildren()[1267],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[119],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[112],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[114],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[103],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[104],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[115],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[118],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[117],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[120],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[106],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[105],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[102],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[113],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[110],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[111],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[121],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[109],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[108],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[107],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[116],
        workspace.Towers.CoU.Obby:GetChildren()[1269],
        workspace.Towers.CoU.Obby:GetChildren()[1293],
        workspace.Towers.CoU.Obby:GetChildren()[1908],
        workspace.Towers.CoU.Obby:GetChildren()[1909],
        workspace.Towers.CoU.Obby:GetChildren()[1294],
        workspace.Towers.CoU.Obby:GetChildren()[1907],
        workspace.Towers.CoU.Obby:GetChildren()[1296],
        workspace.Towers.CoU.Obby:GetChildren()[1297],
        workspace.Towers.CoU.Obby:GetChildren()[1298],
        workspace.Towers.CoU.Obby:GetChildren()[1522],
        workspace.Towers.CoU.Obby:GetChildren()[1525],
        workspace.Towers.CoU.Obby:GetChildren()[1463],
        workspace.Towers.CoU.Obby:GetChildren()[1301],
        workspace.Towers.CoU.Obby:GetChildren()[1302],
        workspace.Towers.CoU.Obby:GetChildren()[1303],
        workspace.Towers.CoU.Obby:GetChildren()[1516],
        workspace.Towers.CoU.Obby:GetChildren()[1299],
        workspace.ClientParts:GetChildren()[12]:GetChildren()[3],
        workspace.Towers.CoU.Obby:GetChildren()[1306],
        workspace.Towers.CoU.Obby:GetChildren()[1307],
        workspace.Towers.CoU.Obby:GetChildren()[1310],
        workspace.Towers.CoU.Obby:GetChildren()[1309],
        workspace.Towers.CoU.Obby:GetChildren()[1308],
        workspace.Towers.CoU.Obby:GetChildren()[1312],
        workspace.Towers.CoU.Obby:GetChildren()[1314],
        workspace.Towers.CoU.Obby:GetChildren()[1311],
        workspace.Towers.CoU.Obby:GetChildren()[1315],
        workspace.Towers.CoU.Obby:GetChildren()[1316],
        workspace.Towers.CoU.Obby:GetChildren()[1317],
        workspace.Towers.CoU.Obby:GetChildren()[1318],
        workspace.Towers.CoU.Obby:GetChildren()[1320],
        workspace.ClientParts:GetChildren()[29]:GetChildren()[1],
        workspace.Towers.CoU.Obby:GetChildren()[1322],
        workspace.Towers.CoU.Obby:GetChildren()[1324],
        workspace.Towers.CoU.Obby:GetChildren()[1321],
        workspace.Towers.CoU.Obby:GetChildren()[1334],
        workspace.Towers.CoU.Obby:GetChildren()[1331],
        workspace.Towers.CoU.Obby:GetChildren()[1335],
        workspace.Towers.CoU.Obby:GetChildren()[1336],
        workspace.Towers.CoU.Obby:GetChildren()[1337],
        workspace.Towers.CoU.Obby:GetChildren()[1338],
        workspace.Towers.CoU.Obby:GetChildren()[1339],
        workspace.Towers.CoU.Obby:GetChildren()[1341],
        workspace.Towers.CoU.Obby:GetChildren()[1340],
        workspace.Towers.CoU.Obby:GetChildren()[1342],
        workspace.Towers.CoU.Obby:GetChildren()[1343],
        workspace.Towers.CoU.Obby:GetChildren()[1910],
        workspace.Towers.CoU.Obby:GetChildren()[1344],
        workspace.Towers.CoU.Obby:GetChildren()[1345],
        workspace.Towers.CoU.Obby:GetChildren()[1346],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[98],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[88],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[97],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[96],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[94],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[95],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[93],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[92],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[91],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[90],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[89],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[101],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[100],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[87],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[83],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[85],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[86],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[84],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[82],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[99],
        workspace.Towers.CoU.Obby:GetChildren()[1347],
        workspace.Towers.CoU.Obby:GetChildren()[1369],
        workspace.Towers.CoU.Obby:GetChildren()[1371],
        workspace.Towers.CoU.Obby:GetChildren()[1372],
        workspace.Towers.CoU.Obby:GetChildren()[1374],
        workspace.Towers.CoU.Obby:GetChildren()[1375],
        workspace.ClientParts:GetChildren()[11]:GetChildren()[1],
        workspace.ClientParts:GetChildren()[5]:GetChildren()[1],
        workspace.ClientParts:GetChildren()[28]:GetChildren()[1],
        workspace.ClientParts:GetChildren()[1]:GetChildren()[1],
        workspace.ClientParts:GetChildren()[4]:GetChildren()[1],
        workspace.Towers.CoU.Obby:GetChildren()[903],
        workspace.ClientParts:GetChildren()[24]:GetChildren()[2],
        workspace.Towers.CoU.Obby:GetChildren()[1376],
        workspace.Towers.CoU.Obby:GetChildren()[1378],
        workspace.Towers.CoU.Obby:GetChildren()[1368],
        workspace.Towers.CoU.Obby:GetChildren()[1383],
        workspace.Towers.CoU.Obby:GetChildren()[1382],
        workspace.Towers.CoU.Obby:GetChildren()[1385],
        workspace.Towers.CoU.Obby:GetChildren()[1388],
        workspace.Towers.CoU.Obby:GetChildren()[1387],
        workspace.Towers.CoU.Obby:GetChildren()[1389],
        workspace.Towers.CoU.Obby:GetChildren()[1393],
        workspace.Towers.CoU.Obby:GetChildren()[1392],
        workspace.Towers.CoU.Obby:GetChildren()[1394],
        workspace.Towers.CoU.Obby:GetChildren()[1396],
        workspace.Towers.CoU.Obby:GetChildren()[1398],
        workspace.Towers.CoU.Obby:GetChildren()[1397],
        workspace.Towers.CoU.Obby:GetChildren()[1399],
        workspace.Towers.CoU.Obby:GetChildren()[1400],
        workspace.Towers.CoU.Obby:GetChildren()[1401],
        workspace.Towers.CoU.Obby:GetChildren()[1402],
        workspace.Towers.CoU.Obby:GetChildren()[1404],
        workspace.Towers.CoU.Obby:GetChildren()[1405],
        workspace.Towers.CoU.Obby:GetChildren()[1411],
        workspace.Towers.CoU.Obby:GetChildren()[1406],
        workspace.Towers.CoU.Obby:GetChildren()[1414],
        workspace.Towers.CoU.Obby:GetChildren()[1415],
        workspace.Towers.CoU.Obby:GetChildren()[1416],
        workspace.Towers.CoU.Obby:GetChildren()[1418],
        workspace.Towers.CoU.Obby:GetChildren()[1419],
        workspace.Towers.CoU.Obby:GetChildren()[1420],
        workspace.Towers.CoU.Obby:GetChildren()[1421],
        workspace.Towers.CoU.Obby:GetChildren()[1426],
        workspace.Towers.CoU.Obby:GetChildren()[1413],
        workspace.Towers.CoU.Obby:GetChildren()[1716],
        workspace.Towers.CoU.Obby:GetChildren()[1427],
        workspace.Towers.CoU.Obby:GetChildren()[1428],
        workspace.Towers.CoU.Obby:GetChildren()[1429],
        workspace.Towers.CoU.Obby:GetChildren()[895],
        workspace.Towers.CoU.Obby:GetChildren()[896],
        workspace.Towers.CoU.Obby:GetChildren()[899],
        workspace.Towers.CoU.Obby:GetChildren()[900],
        workspace.Towers.CoU.Obby:GetChildren()[898],
        workspace.Towers.CoU.Obby:GetChildren()[1465],
        workspace.Towers.CoU.Obby:GetChildren()[901],
        workspace.Towers.CoU.Obby:GetChildren()[1466],
        workspace.Towers.CoU.Obby:GetChildren()[1469],
        workspace.Towers.CoU.Obby:GetChildren()[1464],
        workspace.Towers.CoU.Obby:GetChildren()[1468],
        workspace.Towers.CoU.Obby:GetChildren()[1472],
        workspace.Towers.CoU.Obby:GetChildren()[1471],
        workspace.Towers.CoU.Obby:GetChildren()[1470],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[212],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[190],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[207],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[195],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[219],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[203],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[199],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[204],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[193],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[202],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[198],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[215],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[197],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[196],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[194],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[192],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[191],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[218],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[50],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[208],
        workspace.ClientParts:GetChildren()[3]:GetChildren()[2],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[26],
        workspace.Towers.CoU.Obby:GetChildren()[361],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[2],
        workspace.Towers.CoU.Obby:GetChildren()[345],
        workspace.Towers.CoU.Obby:GetChildren()[1497],
        workspace.ClientParts:GetChildren()[26]:GetChildren()[3],
        workspace.Towers.CoU.Obby:GetChildren()[1502],
        workspace.Towers.CoU.Obby:GetChildren()[1505],
        workspace.Towers.CoU.Obby:GetChildren()[1508],
        workspace.Towers.CoU.Obby:GetChildren()[1509],
        workspace.Towers.CoU.Obby:GetChildren()[1510],
        workspace.Towers.CoU.Obby:GetChildren()[1511],
        workspace.Towers.CoU.Obby:GetChildren()[1512],
        workspace.Towers.CoU.Obby:GetChildren()[1504],
        workspace.Towers.CoU.Obby:GetChildren()[1503],
        workspace.Towers.CoU.Obby:GetChildren()[1527],
        workspace.Towers.CoU.Obby:GetChildren()[558],
        workspace.Towers.CoU.Obby:GetChildren()[1528],
        workspace.Towers.CoU.Obby:GetChildren()[1530],
        workspace.ClientParts:GetChildren()[18]:GetChildren()[1],
        workspace.Towers.CoU.Obby:GetChildren()[1534],
        workspace.Towers.CoU.Obby:GetChildren()[1536],
        workspace.Towers.CoU.Obby:GetChildren()[1537],
        workspace.Towers.CoU.Obby:GetChildren()[1540],
        workspace.Towers.CoU.Obby:GetChildren()[1544],
        workspace.Towers.CoU.Obby:GetChildren()[1546],
        workspace.Towers.CoU.Obby:GetChildren()[1922],
        workspace.Towers.CoU.Obby:GetChildren()[1547],
        workspace.Towers.CoU.Obby:GetChildren()[1548],
        workspace.Towers.CoU.Obby:GetChildren()[1549],
        workspace.Towers.CoU.Obby:GetChildren()[1552],
        workspace.Towers.CoU.Obby:GetChildren()[1554],
        workspace.Towers.CoU.Obby:GetChildren()[1556],
        workspace.Towers.CoU.Obby:GetChildren()[1557],
        workspace.Towers.CoU.Obby:GetChildren()[1566],
        workspace.Towers.CoU.Obby:GetChildren()[1567],
        workspace.Towers.CoU.Obby:GetChildren()[1569],
        workspace.Towers.CoU.Obby:GetChildren()[1578],
        workspace.Towers.CoU.Obby:GetChildren()[5],
        workspace.Towers.CoU.Obby:GetChildren()[1576],
        workspace.Towers.CoU.Obby:GetChildren()[1582],
        workspace.Towers.CoU.Obby:GetChildren()[349],
        workspace.Towers.CoU.Obby:GetChildren()[347],
        workspace.Towers.CoU.Obby:GetChildren()[1589],
        workspace.Towers.CoU.Obby:GetChildren()[321],
        workspace.Towers.CoU.Obby:GetChildren()[1579],
        workspace.ClientParts:GetChildren()[14]:GetChildren()[4],
        workspace.Towers.CoU.Obby:GetChildren()[1584],
        workspace.Towers.CoU.Obby:GetChildren()[1585],
        workspace.ClientParts:GetChildren()[14]:GetChildren()[5],
        workspace.Towers.CoU.Obby:GetChildren()[338],
        workspace.Towers.CoU.Obby:GetChildren()[323],
        workspace.Towers.CoU.Obby:GetChildren()[1590],
        workspace.Towers.CoU.Obby:GetChildren()[1943],
        workspace.Towers.CoU.Obby:GetChildren()[1234],
        workspace.Towers.CoU.Obby:GetChildren()[307],
        workspace.Towers.CoU.Obby:GetChildren()[340],
        workspace.Towers.CoU.Obby:GetChildren()[337],
        workspace.Towers.CoU.Obby:GetChildren()[343],
        workspace.Towers.CoU.Obby:GetChildren()[354],
        workspace.Towers.CoU.Obby:GetChildren()[336],
        workspace.Towers.CoU.Obby:GetChildren()[342],
        workspace.Towers.CoU.Obby:GetChildren()[2],
        workspace.Towers.CoU.Obby:GetChildren()[802],
        workspace.Towers.CoU.Obby:GetChildren()[1586],
        workspace.Towers.CoU.Obby:GetChildren()[1591],
        workspace.Towers.CoU.Obby:GetChildren()[1592],
        workspace.Towers.CoU.Obby:GetChildren()[1593],
        workspace.Towers.CoU.Obby:GetChildren()[1594],
        workspace.Towers.CoU.Obby:GetChildren()[1595],
        workspace.Towers.CoU.Obby:GetChildren()[1598],
        workspace.Towers.CoU.Obby:GetChildren()[1599],
        workspace.Towers.CoU.Obby:GetChildren()[1602],
        workspace.Towers.CoU.Obby:GetChildren()[1603],
        workspace.Towers.CoU.Obby:GetChildren()[1609],
        workspace.Towers.CoU.Obby:GetChildren()[365],
        workspace.Towers.CoU.Obby:GetChildren()[348],
        workspace.Towers.CoU.Obby:GetChildren()[364],
        workspace.Towers.CoU.Obby:GetChildren()[367],
        workspace.Towers.CoU.Obby:GetChildren()[368],
        workspace.Towers.CoU.Obby:GetChildren()[693],
        workspace.Towers.CoU.Obby:GetChildren()[371],
        workspace.Towers.CoU.Obby:GetChildren()[374],
        workspace.Towers.CoU.Obby:GetChildren()[370],
        workspace.Towers.CoU.Obby:GetChildren()[375],
        workspace.Towers.CoU.Obby:GetChildren()[376],
        workspace.Towers.CoU.Obby:GetChildren()[332],
        workspace.Towers.CoU.Obby:GetChildren()[379],
        workspace.Towers.CoU.Obby:GetChildren()[378],
        workspace.Towers.CoU.Obby:GetChildren()[377],
        workspace.Towers.CoU.Obby:GetChildren()[608],
        workspace.Towers.CoU.Obby:GetChildren()[601],
        workspace.Towers.CoU.Obby:GetChildren()[602],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[70],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[77],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[76],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[81],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[62],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[78],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[51],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[73],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[75],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[61],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[74],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[60],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[56],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[71],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[55],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[54],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[53],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[57],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[52],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[72],
        workspace.Towers.CoU.Obby:GetChildren()[616],
        workspace.Towers.CoU.Obby:GetChildren()[687],
        workspace.Towers.CoU.Obby:GetChildren()[690],
        workspace.ClientParts:GetChildren()[69]:GetChildren()[1],
        workspace.Towers.CoU.Obby:GetChildren()[1154],
        workspace.Towers.CoU.Obby:GetChildren()[1155],
        workspace.Towers.CoU.Obby:GetChildren()[1156],
        workspace.Towers.CoU.Obby:GetChildren()[1157],
        workspace.Towers.CoU.Obby:GetChildren()[1438],
        workspace.Towers.CoU.Obby:GetChildren()[1437],
        workspace.Towers.CoU.Obby:GetChildren()[692],
        workspace.Towers.CoU.Obby:GetChildren()[680],
        workspace.ClientParts:GetChildren()[70]:GetChildren()[1],
        workspace.ClientParts:GetChildren()[71]:GetChildren()[1],
        workspace.ClientParts:GetChildren()[71]:GetChildren()[2],
        workspace.Towers.CoU.Obby:GetChildren()[1433],
        workspace.Towers.CoU.Obby:GetChildren()[1449],
        workspace.Towers.CoU.Obby:GetChildren()[1435],
        workspace.Towers.CoU.Obby:GetChildren()[678],
        workspace.Towers.CoU.Obby:GetChildren()[1485],
        workspace.Towers.CoU.Obby:GetChildren()[691],
        workspace.Towers.CoU.Obby:GetChildren()[1473],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[28],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[14],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[7],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[46],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[19],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[37],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[9],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[35],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[39],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[36],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[11],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[4],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[31],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[8],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[24],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[3],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[38],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[34],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[20],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[64],
        workspace.Towers.CoU.Obby:GetChildren()[1481],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[68],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[79],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[67],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[66],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[65],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[63],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[59],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[58],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[41],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[49],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[43],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[45],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[27],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[21],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[10],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[16],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[40],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[22],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[26],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[69],
        workspace.Towers.CoU.Obby:GetChildren()[1479],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[6],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[33],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[15],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[2],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[47],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[32],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[1],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[48],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[13],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[18],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[25],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[44],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[30],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[17],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[42],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[29],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[12],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[5],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[23],
        workspace.Towers.CoU.Obby["tightrope parts"]:GetChildren()[80],
        workspace.Towers.CoU.Obby:GetChildren()[1483],
        workspace.Towers.CoU.Obby:GetChildren()[1161],
        workspace.Towers.CoU.Obby:GetChildren()[1153],
        workspace.Towers.CoU.Obby:GetChildren()[1164],
        workspace.Towers.CoU.Obby:GetChildren()[1162],
        workspace.Towers.CoU.Obby:GetChildren()[1163],
        workspace.ClientParts:GetChildren()[72]:GetChildren()[2],
        workspace.Towers.CoU.Obby:GetChildren()[1166],
        workspace.Towers.CoU.Obby:GetChildren()[1171],
        workspace.Towers.CoU.Obby:GetChildren()[1286],
        workspace.Towers.CoU.Obby:GetChildren()[1279],
        workspace.Towers.CoU.Obby:GetChildren()[1271],
        workspace.Towers.CoU.Obby:GetChildren()[1172],
        workspace.Towers.CoU.Obby:GetChildren()[1170],
        workspace.Towers.CoU.Obby:GetChildren()[1278],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[29],
        workspace.Towers.CoU.Obby:GetChildren()[1270],
        workspace.Towers.CoU.Obby:GetChildren()[1276],
        workspace.Towers.CoU.Obby:GetChildren()[1287],
        workspace.Towers.CoU.Obby:GetChildren()[1289],
        workspace.Towers.CoU.Obby:GetChildren()[1280],
        workspace.Towers.CoU.Obby:GetChildren()[1351],
        workspace.Towers.CoU.Obby:GetChildren()[1354],
        workspace.Towers.CoU.Obby:GetChildren()[1355],
        workspace.Towers.CoU.Obby:GetChildren()[1281],
        workspace.Towers.CoU.Obby:GetChildren()[1436],
        workspace.Towers.CoU.Obby:GetChildren()[1277],
        workspace.Towers.CoU.Obby:GetChildren()[1274],
        workspace.Towers.CoU.Obby:GetChildren()[1348],
        workspace.Towers.CoU.Obby:GetChildren()[1361],
        workspace.Towers.CoU.Obby:GetChildren()[1349],
        workspace.Towers.CoU.Obby:GetChildren()[1360],
        workspace.Towers.CoU.Obby:GetChildren()[695],
        workspace.Towers.CoU.Obby:GetChildren()[1282],
        workspace.Towers.CoU.Obby:GetChildren()[1356],
        workspace.Towers.CoU.Obby:GetChildren()[1357],
        workspace.Towers.CoU.Obby:GetChildren()[1359],
        workspace.Towers.CoU.Obby:GetChildren()[1350],
        workspace.Towers.CoU.Obby:GetChildren()[1362],
        workspace.Towers.CoU.Obby:GetChildren()[1367],
        workspace.Towers.CoU.Obby:GetChildren()[1486],
        workspace.Towers.CoU.Obby:GetChildren()[610],
        workspace.Towers.CoU.Obby:GetChildren()[607],
        workspace.Towers.CoU.Obby:GetChildren()[603],
        workspace.Towers.CoU.Obby:GetChildren()[609],
        workspace.Towers.CoU.Obby:GetChildren()[615],
        workspace.Towers.CoU.Obby:GetChildren()[618],
        workspace.Towers.CoU.Obby:GetChildren()[599],
        workspace.Towers.CoU.Obby:GetChildren()[1484],
        workspace.Towers.CoU.Obby:GetChildren()[1487],
        workspace.Towers.CoU.Obby:GetChildren()[1366],
        workspace.Towers.CoU.Obby:GetChildren()[1363],
        workspace.Towers.CoU.Obby:GetChildren()[612],
        workspace.Towers.CoU.Obby:GetChildren()[614],
        workspace.Towers.CoU.Obby:GetChildren()[600],
        workspace.Towers.CoU.Obby:GetChildren()[1488],
        workspace.Towers.CoU.Obby:GetChildren()[679],
        workspace.Towers.CoU.Obby:GetChildren()[1477],
        workspace.ClientParts:GetChildren()[73]:GetChildren()[3],
        workspace.Towers.CoU.Obby:GetChildren()[684],
        workspace.Towers.CoU.Obby:GetChildren()[1075],
        workspace.Towers.CoU.Obby:GetChildren()[1904],
        workspace.Towers.CoU.Obby:GetChildren()[685],
        workspace.Towers.CoU.Obby:GetChildren()[605],
        workspace.ClientParts.KillBricks:GetChildren()[80],
        workspace.Towers.CoU.Obby:GetChildren()[1070],
        workspace.Towers.CoU.Obby:GetChildren()[1444],
        workspace.Towers.CoU.Obby:GetChildren()[1073],
        workspace.Towers.CoU.Obby:GetChildren()[1692],
        workspace.Towers.CoU.Obby:GetChildren()[1443],
        workspace.Towers.CoU.Obby:GetChildren()[1442],
        workspace.Towers.CoU.Obby:GetChildren()[976],
        workspace.Towers.CoU.Obby:GetChildren()[965],
        workspace.Towers.CoU.Obby:GetChildren()[970],
        workspace.Towers.CoU.Obby:GetChildren()[1475],
        workspace.Towers.CoU.Obby:GetChildren()[966],
        workspace.Towers.CoU.Obby:GetChildren()[975],
        workspace.ClientParts:GetChildren()[74]:GetChildren()[3],
        workspace.Towers.CoU.Obby:GetChildren()[1079],
        workspace.Towers.CoU.Obby:GetChildren()[1687],
        workspace.ClientParts:GetChildren()[75]:GetChildren()[3],
        workspace.Towers.CoU.Obby:GetChildren()[1439],
        workspace.Towers.CoU.Obby:GetChildren()[1077],
        workspace.Towers.CoU.Obby:GetChildren()[1080],
        workspace.Towers.CoU.Obby:GetChildren()[1076],
        workspace.Towers.CoU.Obby:GetChildren()[962],
        workspace.Towers.CoU.Obby:GetChildren()[1069],
        workspace.Towers.CoU.Obby:GetChildren()[1063],
        workspace.Towers.CoU.Obby:GetChildren()[960],
        workspace.ClientParts:GetChildren()[67]:GetChildren()[2],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[30],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[31],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[32],
        workspace.Towers.CoU.Obby:GetChildren()[964],
        workspace.Towers.CoU.Obby:GetChildren()[971],
        workspace.Towers.CoU.Obby:GetChildren()[1067],
        workspace.Towers.CoU.Obby:GetChildren()[1941],
        workspace.Towers.CoU.Obby:GetChildren()[224],
        workspace.Towers.CoU.Obby:GetChildren()[220],
        workspace.Towers.CoU.Obby:GetChildren()[1545],
        workspace.Towers.CoU.Obby:GetChildren()[415],
        workspace.Towers.CoU.Obby:GetChildren()[1890],
        workspace.Towers.CoU.Obby:GetChildren()[1491],
        workspace.Towers.CoU.Obby:GetChildren()[1613],
        workspace.Towers.CoU.Obby:GetChildren()[1944],
        workspace.Towers.CoU.Obby:GetChildren()[1612],
        workspace.Towers.CoU.Obby:GetChildren()[1614],
        workspace.Towers.CoU.Obby:GetChildren()[1615],
        workspace.Towers.CoU.Obby:GetChildren()[1616],
        workspace.Towers.CoU.Obby:GetChildren()[112],
        workspace.Towers.CoU.Obby:GetChildren()[1620],
        workspace.Towers.CoU.Obby:GetChildren()[1621],
        workspace.Towers.CoU.Obby:GetChildren()[1618],
        workspace.Towers.CoU.Obby:GetChildren()[1617],
        workspace.Towers.CoU.Obby:GetChildren()[1577],
        workspace.Towers.CoU.Obby:GetChildren()[1630],
        workspace.Towers.CoU.Obby:GetChildren()[1677],
        workspace.Towers.CoU.Obby:GetChildren()[1693],
        workspace.Towers.CoU.Obby:GetChildren()[1694],
        workspace.Towers.CoU.Obby:GetChildren()[1695],
        workspace.Towers.CoU.Obby:GetChildren()[1697],
        workspace.Towers.CoU.Obby:GetChildren()[1690],
        workspace.Towers.CoU.Obby:GetChildren()[1698],
        workspace.Towers.CoU.Obby:GetChildren()[1699],
        workspace.Towers.CoU.Obby:GetChildren()[1700],
        workspace.Towers.CoU.Obby:GetChildren()[1701],
        workspace.Towers.CoU.Obby:GetChildren()[351],
        workspace.Towers.CoU.Obby:GetChildren()[1719],
        workspace.Towers.CoU.Obby:GetChildren()[1721],
        workspace.Towers.CoU.Obby:GetChildren()[25],
        workspace.Towers.CoU.Obby:GetChildren()[1703],
        workspace.Towers.CoU.Obby:GetChildren()[1705],
        workspace.Towers.CoU.Obby:GetChildren()[1708],
        workspace.Towers.CoU.Obby:GetChildren()[1732],
        workspace.Towers.CoU.Obby:GetChildren()[1709],
        workspace.Towers.CoU.Obby:GetChildren()[1710],
        workspace.Towers.CoU.Obby:GetChildren()[1711],
        workspace.Towers.CoU.Obby:GetChildren()[1712],
        workspace.Towers.CoU.Obby:GetChildren()[1713],
        workspace.Towers.CoU.Obby:GetChildren()[1196],
        workspace.Towers.CoU.Obby:GetChildren()[1714],
        workspace.Towers.CoU.Obby:GetChildren()[1717],
        workspace.Towers.CoU.Obby:GetChildren()[1720],
        workspace.Towers.CoU.Obby:GetChildren()[1722],
        workspace.Towers.CoU.Obby:GetChildren()[1727],
        workspace.Towers.CoU.Obby:GetChildren()[1725],
        workspace.Towers.CoU.Obby:GetChildren()[1940],
        workspace.Towers.CoU.Obby:GetChildren()[1939],
        workspace.Towers.CoU.Obby:GetChildren()[1741],
        workspace.ClientParts.JumpPad,
        workspace.Towers.CoU.Obby:GetChildren()[1803],
        workspace.Towers.CoU.Obby:GetChildren()[1788],
        workspace.ClientParts:GetChildren()[6]:GetChildren()[2],
        workspace.Towers.CoU.Obby:GetChildren()[1794],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[5],
        workspace.Towers.CoU.Obby:GetChildren()[1797],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[4],
        workspace.Towers.CoU.Obby:GetChildren()[1802],
        workspace.Towers.CoU.Obby:GetChildren()[1804],
        workspace.Towers.CoU.Obby:GetChildren()[1808],
        workspace.Towers.CoU.Obby:GetChildren()[1806],
        workspace.Towers.CoU.Obby:GetChildren()[1810],
        workspace.Towers.CoU.Obby:GetChildren()[1811],
        workspace.Towers.CoU.Obby:GetChildren()[1812],
        workspace.Towers.CoU.Obby:GetChildren()[1814],
        workspace.Towers.CoU.Obby:GetChildren()[1813],
        workspace.Towers.CoU.Obby:GetChildren()[1815],
        workspace.Towers.CoU.Obby:GetChildren()[1817],
        workspace.Towers.CoU.Obby:GetChildren()[1818],
        workspace.Towers.CoU.Obby:GetChildren()[1829],
        workspace.Towers.CoU.Obby:GetChildren()[1707],
        workspace.Towers.CoU.Obby:GetChildren()[1832],
        workspace.Towers.CoU.Obby:GetChildren()[916],
        workspace.Towers.CoU.Obby:GetChildren()[1835],
        workspace.Towers.CoU.Obby:GetChildren()[1836],
        workspace.Towers.CoU.Obby:GetChildren()[1837],
        workspace.Towers.CoU.Obby:GetChildren()[1840],
        workspace.Towers.CoU.Obby:GetChildren()[1839],
        workspace.Towers.CoU.Obby:GetChildren()[1841],
        workspace.Towers.CoU.Obby:GetChildren()[1842],
        workspace.Towers.CoU.Obby:GetChildren()[1844],
        workspace.Towers.CoU.Obby:GetChildren()[1816],
        workspace.Towers.CoU.Obby:GetChildren()[1845],
        workspace.Towers.CoU.Obby:GetChildren()[1846],
        workspace.ClientParts:GetChildren()[2]:GetChildren()[3],
        workspace.Towers.CoU.Obby:GetChildren()[1848],
        workspace.Towers.CoU.Obby:GetChildren()[1852],
        workspace.Towers.CoU.Obby:GetChildren()[1851],
        workspace.Towers.CoU.Obby:GetChildren()[1854],
        workspace.Towers.CoU.Obby:GetChildren()[1853],
        workspace.Towers.CoU.Obby:GetChildren()[1855],
        workspace.Towers.CoU.Obby:GetChildren()[1856],
        workspace.Towers.CoU.Obby:GetChildren()[1859],
        workspace.Towers.CoU.Obby:GetChildren()[1860],
        workspace.Towers.CoU.Obby:GetChildren()[1861],
        workspace.Towers.CoU.Obby:GetChildren()[1863],
        workspace.Towers.CoU.Obby:GetChildren()[1864],
        workspace.Towers.CoU.Obby:GetChildren()[1865],
        workspace.Towers.CoU.Obby:GetChildren()[1871],
        workspace.Towers.CoU.Obby:GetChildren()[1872],
        workspace.Towers.CoU.Obby:GetChildren()[1873],
        workspace.ClientParts:GetChildren()[9]:GetChildren()[1],
        workspace.ClientParts:GetChildren()[9]:GetChildren()[4],
        workspace.Towers.CoU.Obby:GetChildren()[1875],
        workspace.Towers.CoU.Obby:GetChildren()[1879],
        workspace.Towers.CoU.Obby:GetChildren()[1880],
        workspace.Towers.CoU.Obby:GetChildren()[1883],
        workspace.Towers.CoU.Obby:GetChildren()[1884],
        workspace.Towers.CoU.Obby:GetChildren()[1888],
        workspace.Towers.CoU.Obby:GetChildren()[1889],
        workspace.Towers.CoU.Obby:GetChildren()[1895],
        workspace.Towers.CoU.Obby:GetChildren()[1896],
        workspace.Towers.CoU.Obby:GetChildren()[1897],
        workspace.Towers.CoU.Obby:GetChildren()[1893],
        workspace.Towers.CoU.Obby:GetChildren()[1891],
        workspace.Towers.CoU.Obby:GetChildren()[1892],
        workspace.Towers.CoU.Obby:GetChildren()[1886],
        workspace.Towers.CoU.Obby:GetChildren()[327],
        workspace.Towers.CoU.Obby:GetChildren()[1899],
        workspace.Towers.CoU.Obby:GetChildren()[1977],
        workspace.Towers.CoU.Obby:GetChildren()[1978],
        workspace.Towers.CoU.Obby:GetChildren()[1626],
        workspace.Towers.CoU.Obby:GetChildren()[1982],
        workspace.Towers.CoU.Obby:GetChildren()[1983],
        workspace.Towers.CoU.Obby:GetChildren()[1984],
        workspace.Towers.CoU.Obby:GetChildren()[1979],
        workspace.Towers.CoU.Obby:GetChildren()[1986],
        workspace.Towers.CoU.Obby:GetChildren()[1985],
        workspace.Towers.CoU.Obby:GetChildren()[1989],
        workspace.Towers.CoU.Obby:GetChildren()[1988],
        workspace.Towers.CoU.Obby:GetChildren()[1987],
        workspace.Towers.CoU.Obby:GetChildren()[1993],
        workspace.Towers.CoU.Obby:GetChildren()[1992],
        workspace.Towers.CoU.Obby:GetChildren()[1990],
        workspace.Towers.CoU.Obby:GetChildren()[1991],
        workspace.Towers.CoU.Obby:GetChildren()[1997],
        workspace.Towers.CoU.Obby:GetChildren()[1996],
        workspace.Towers.CoU.Obby:GetChildren()[1995],
        workspace.Towers.CoU.Obby:GetChildren()[1994],
        workspace.Towers.CoU.Obby:GetChildren()[1980],
        workspace.Towers.CoU.Obby:GetChildren()[7],
        workspace.Towers.CoU.Obby:GetChildren()[1998],
        workspace.Towers.CoU.Obby:GetChildren()[37],
        workspace.Towers.CoU.Obby:GetChildren()[1900],
        workspace.Towers.CoU.Obby:GetChildren()[1684],
        workspace.Towers.CoU.Obby:GetChildren()[12],
        workspace.Towers.CoU.Obby:GetChildren()[6],
        workspace.Towers.CoU.Obby:GetChildren()[11],
        workspace.Towers.CoU.Obby:GetChildren()[161],
        workspace.Towers.CoU.Obby:GetChildren()[1040],
        workspace.ClientParts:GetChildren()[31]:GetChildren()[1],
        workspace.Towers.CoU.Obby:GetChildren()[4],
        workspace.Towers.CoU.Obby:GetChildren()[9],
        workspace.Towers.CoU.Obby:GetChildren()[1917],
        workspace.Towers.CoU.Obby:GetChildren()[3],
        workspace.Towers.CoU.Obby:GetChildren()[1],
        workspace.Towers.CoU.Obby:GetChildren()[1916],
        workspace.Towers.CoU.Obby:GetChildren()[643],
        workspace.Towers.CoU.Obby:GetChildren()[510],
        workspace.Towers.CoU.Obby:GetChildren()[511],
        workspace.Towers.CoU.Obby:GetChildren()[512],
        workspace.Towers.CoU.WinPad
    }
end
